## postgres image repository
image: "nats"
## postgres image version
## ref: https://hub.docker.com/r/library/postgres/tags/
##
imageTag: "0.9.4"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# number of Nats replicas
# by default 1
# replicaCount: 1

# Nats port for clients
clientPort: 4222
clientTargetPort: 4222

# HTTP monitoring port
httpPort: 8222
httpTargetPort: 8222

# Route connections to be received on any interface on port 6222
clusterPort: 6222
clusterTargetPort: 6222

# service type
svcType: ClusterIP

# cluser IP
svcClusterIP: None

# restart policy
restartPolicy: Always

# Nats bind address (default: 0.0.0.0)
addr: 0.0.0.0

# service configuration
service:
  annotations:
    pod.alpha.kubernetes.io/initialized: "true"

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m