{{ $cfCommonTplSemver := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
{{ $values := .Values.runtimeImages }}
{{- if .Values.ci.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  {{- /* dummy template just to list runtime images */}}
  name: {{ include "codefresh.fullname" . }}-images
  labels:
    {{- include "codefresh.labels" . | nindent 4 }}
  annotations:
    {{- with $values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  images: |
    {{- range $key, $val := $values }}
    image: {{ $val }}
    {{- end }}
{{- end }}