---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-controller
  labels:
    app: {{ template "fullname" . }}-controller
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
data:
  disable-access-log: {{ default "false" .Values.disableAccessLog | quote }}
  enable-vts-status: "true"
