---
# kind: scheduler-kubernetes
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  type: {{ .Values.svcType }}
  ports:
  - name: "client"
    port: {{ .Values.clientPort }}
    protocol: TCP
    targetPort: {{ .Values.clientTargetPort }}
  - name: "http"
    port: {{ .Values.httpPort }}
    protocol: TCP
    targetPort: {{ .Values.httpTargetPort }}
  - name: "clusterig"
    port: {{ .Values.clusterPort }}
    protocol: TCP
    targetPort: {{ .Values.clusterTargetPort }}
  # This is a headless service, Kubernetes won't assign a VIP for it.
  # *.nats.codefresh.svc.cluster.local
  clusterIP: {{ .Values.svcClusterIP }}
  selector:
    app: {{ template "fullname" . }}

