{{- if not ( include "registry.existingPvc" . ) -}}

{{- $storageClass :=  ( include "registry.storageClass" . ) -}}
{{- $storageSize :=  ( include "registry.storageSize" . ) -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if $storageClass }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}    
  resources:
    requests:
      storage: {{ $storageSize }}
{{- end }}