apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  {{- if .Values.service }}
  type: {{ default "ClusterIP" .Values.service.type | quote }}
  {{- end }}
  ports:
  - name: {{ template "fullname" . }}
    port: {{ .Values.port }}
    protocol: TCP
  selector:
    app:  {{ template "fullname" . }}

