apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-certs-client
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  ca.pem: |
    {{ .Values.clientCertsCA }} 
  cert.pem: |
    {{ .Values.clientCertsCert }} 
  key.pem: |
    {{ .Values.clientCertsKey }} 
