kind: Secret
metadata:
  name: {{ template "fullname" . }}-node-clusters
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
apiVersion: v1
stringData:
  kube-config: |
    apiVersion: v1
    clusters:
    {{- range $, $cluster := .Values.nodeClusters }}
    - cluster:
        certificate-authority-data: {{ $cluster.certificateAuthorityData }}
        server: {{ $cluster.server }}
      name: {{ $cluster.name }}
    {{- end }}
    contexts:
    {{- range $, $context := .Values.nodeContexts }}
    - context:
        cluster: {{ $context.cluster }}
        user: {{ $context.user }}
      name: {{ $context.name }}
    {{- end }}
    current-context: {{ .Values.nodeCurrentContext }}
    kind: Config
    preferences: {}
    users:
    {{- range $, $user := .Values.nodeUsers }}
    - name: {{ $user.name }}
      user:
        client-certificate-data: {{ $user.clientCertificateData }} 
        client-key-data: {{ $user.clientKeyData }}
        password: {{ $user.password }}
        username: {{ $user.username }}
    {{- end }}