{{- if .Values.global.postgresSeedJob.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}-postgres-creds
data:
  user: |-
    {{ required "postgresUser value is required" .Values.global.postgresUser | b64enc }}
  password: |-
    {{ required "postgresPassword value is required" .Values.global.postgresPassword | b64enc }}
  seedJobUser: |-
    {{ .Values.global.postgresSeedJob.user | default .Values.global.postgresUser | b64enc }}
  seedJobPassword: |-
    {{ .Values.global.postgresSeedJob.password | default .Values.global.postgresPassword | b64enc }}
  database: |-
    {{ .Values.global.postgresDatabase | default "codefresh" | b64enc }}
  host: |-
    {{ required "postgresHost value is required" .Values.global.postgresHostname | b64enc }}
  port: |-
    {{ .Values.global.postgresPort | default "5432" | toString | b64enc }}
{{- end }}
