{{ $name := printf "%v-%v-%v" .Release.Name .Values.global.codefresh "registry" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "codefresh.imagePullSecret" . }}
---
{{- if index .Values "argo-platform" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "codefresh.imagePullSecret" . }}
{{- end }}