{{- define "imagePullSecret" }}
{{- printf "{\"auths\": 
{{- range $k, $v := .Values.imageCredentials }}
{\"%s\": {\"auth\": \"%s\"}}}" $v.registry (printf "%s:%s" $v.username $v.password | b64enc) 
{{- end }}
| b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-registry
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }} 