{{- if .Values.webTLS }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-{{ .Values.webTLS.secretName }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  tls.cert: {{ .Values.webTLS.cert | b64enc | quote }}
  tls.key: {{ .Values.webTLS.key | b64enc | quote }}
{{- end }}
