## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always
redeploy: false

# number of replicas
# by default 1
# replicaCount: 1

# image name
image: r.cfcr.io/codefresh-inc/codefresh/payments

# image tag
imageTag: master

# Service type (ClusterIP, NodePort, LoadBalancer)
#serviceType: ClusterIP

# exposed port
port: 9000

# application target port
targetPort: 9000

# service database name
mongodbName: payments

mongoCreateDbJobScript: files/mongoCreateDbJobScript

# formatLogsToElk logs will be formatter as elk expect to read it
formatLogsToElk: true

