{{- if and .Values.seed.enabled (or .Values.global.seedJobs .Values.seed.mongoSeedJob.enabled) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "codefresh.fullname" . }}-mongo-seed
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
stringData:
  MONGODB_ROOT_USER: {{ coalesce .Values.global.mongodbRootUser .Values.seed.mongoSeedJob.mongodbRootUser }}
  MONGODB_ROOT_PASSWORD: {{ urlquery (coalesce .Values.global.mongodbRootPassword .Values.seed.mongoSeedJob.mongodbRootPassword) }}
  MONGODB_URI: {{ .Values.global.mongoURI }}
  MONGODB_DATABASE: {{ .Values.global.mongodbDatabase | default "codefresh" }}
{{- end }}