{{ $libTemplateName := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
{{ $context := deepCopy .Values.seed }}
---
{{- if and .Values.seed.enabled (or .Values.global.seedJobs .Values.seed.mongoSeedJob.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "codefresh.fullname" . }}-mongo-seed
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
spec:
  {{- with .Values.seed.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  {{- with .Values.seed.backoffLimit }}
  backoffLimit: {{ . | int }}
  {{- end }}
  template:
    metadata:
      name: {{ include "codefresh.fullname" . }}-mongo-seed
      labels:
        {{ include "codefresh.labels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imageRegistry }}
      imagePullSecrets:
        - name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-registry"
      {{- end }}
      securityContext:
        {{- toYaml .Values.seed.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "codefresh.fullname" . }}-mongo-seed
        image: {{ include (printf "%s.image.name" $libTemplateName) (dict "image" .Values.seed.mongoSeedJob.image "context" .) }}
        envFrom:
          - secretRef:
              name: {{ include "codefresh.fullname" . }}
        env:
          - name: MONGODB_HOST
          {{- include "codefresh.mongodb-host-env-var-value" . | indent 12 }}
          - name: MONGODB_USER
          {{- include "codefresh.mongodb-user-env-var-value" . | indent 12 }}
          - name: MONGODB_PASSWORD
          {{- include "codefresh.mongodb-password-env-var-value" . | indent 12 }}
          - name: MONGO_URI
          {{- include "codefresh.mongo-seed-uri-env-var-value" . | indent 12 }}
          - name: MONGODB_ROOT_USER
          {{- include "codefresh.mongodb-root-user-env-var-value" . | indent 12 }}
          - name: MONGODB_ROOT_PASSWORD
          {{- include "codefresh.mongodb-root-password-env-var-value" . | indent 12 }}
          - name: DEVELOPMENT_CHART
            value: {{ .Values.developmentChart | quote }}
        command:
          - "/bin/bash"
          - "-exc"
          - |
            {{ .Files.Get "files/mongoSeedJobScript.sh" | nindent 12 }}
        resources:
          {{- toYaml .Values.seed.resources | nindent 10 }}
        volumeMounts:
        - name: seed-data
          mountPath: "/usr/share/extras/accounts.json"
          subPath: "accounts.json"
        - name: seed-data
          mountPath: "/usr/share/extras/users.json"
          subPath: "users.json"
        - name: seed-data
          mountPath: "/usr/share/extras/idps.json"
          subPath: "idps.json"
        - name: seed-data
          mountPath: "/usr/share/extras/packs.json"
          subPath: "idps.json"
      {{- include (printf "%s.volumeMounts" $libTemplateName) ( dict "Values" .Values.seed.volumeMounts "context" $ ) | nindent 8 }}
      {{- with .Values.seed.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.seed.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.seed.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      restartPolicy: OnFailure
      volumes:
      - name: seed-data
        configMap:
          name: {{ include "codefresh.fullname" . }}-mongo-seed
      {{- include (printf "%s.volumes" $libTemplateName) ( dict "Values" .Values.seed.volumes "context" $ ) | nindent 6 }}
{{- end }}
