{{- if and .Values.seed.enabled (or .Values.global.seedJobs .Values.seed.postgresSeedJob.enabled) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "codefresh.fullname" . }}-postgres-seed
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
stringData:
  POSTGRES_USER: {{ .Values.global.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresPassword }}
  POSTGRES_SEED_USER: {{ (coalesce .Values.seed.postgresSeedJob.postgresUser .Values.global.postgresSeedJob.postgresUser) | default .Values.global.postgresUser }}
  POSTGRES_SEED_PASSWORD: {{ (coalesce .Values.seed.postgresSeedJob.postgresPassword .Values.global.postgresSeedJob.postgresPassword) | default .Values.global.postgresPassword }}
  POSTGRES_HOST: {{ default (printf "%s-%s" .Release.Name .Values.global.postgresService) .Values.global.postgresHostname }}
  POSTGRES_PORT: {{ .Values.global.postgresPort | default 5432 | quote }}
{{- end }}