{{- if .Values.rabbit.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbit
  name: rabbit
spec:
  ports:
  - name: rabbit
    port: 5672
    protocol: TCP
    targetPort: rabbit
  - name: rabbit-mng
    port: 15672
    protocol: TCP
    targetPort: rabbit
  selector:
    app: rabbit
  sessionAffinity: None
  type: ClusterIP
{{- end }}