{{- if .Values.rabbit.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbit
  name: rabbit
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rabbit
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: rabbit
    spec:
      containers:
      - image: rabbitmq:3-management
        imagePullPolicy: Always
        name: rabbit
        ports:
        - containerPort: 5672
          name: rabbit
          protocol: TCP
        - containerPort: 15672
          name: rabbit-mng
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 1.5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbit-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rabbit-data
        persistentVolumeClaim:
          claimName: rabbit-data
{{- end }}