{{- if .Values.rabbit.enabled -}}

{{- $storageClass :=  ( include "rabbit.storageClass" . ) -}}
{{- $storageSize :=  ( include "rabbit.storageSize" . ) -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rabbit
  name: rabbit-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $storageSize | quote }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}  
  volumeMode: Filesystem
{{- end }}