# number of replicas
# by default 1
# replicaCount: 1

# image name
image: registry

# image tag
imageTag: 2.6

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# Service type (ClusterIP, NodePort, LoadBalancer)
#serviceType: ClusterIP

# registry port
port: 5000

## Use existing volume claim name
# pvcName:

# registry PVC storage size
storageSize: 100Gi
persistence:
  enabled: true

mainChart: codefresh

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 128Mi
    cpu: 100m

## Node labels and tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
nodeSelector: {}
tolerations: []
