{{- if and (or .Values.gencerts.enabled .Values.global.certsJobs) .Values.gencerts.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codefresh.fullname" . }}-gencerts
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "codefresh.fullname" . }}-gencerts
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "codefresh.fullname" . }}-gencerts
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "codefresh.fullname" . }}-gencerts
subjects:
  - kind: ServiceAccount
    name: {{ include "codefresh.fullname" . }}-gencerts
    namespace: {{ .Release.Namespace }}
{{ end }}