---
#
imagePullPolicy: IfNotPresent

dockercfg: placeholder

# default service port
servicePort: 80

# image with kubectl that can work with our K8s version
kubectlImage: lachlanevenson/k8s-kubectl:v1.6.7

slackAppID: "4027524866.65820083427"
slackAppSecret: placeholder

stripeSecretKey: sk_test_8AnaAlccXXkcPXP7vrgKZQyy
stripePublicKey: ""
stripeWebhookSecret: ""

rollbarAccessToken: ""

logglyToken: invalid-token

firebaseUrl: "https://codefresh-on-prem.firebaseio.com/on-prem"
firebaseSecret: placeholder

ingress:
  enabled: true
  domain: '*'

consul:
  DatacenterName: codefresh-onprem
  Replicas: 1
  Memory: 64Mi

postgresql:
  postgresDatabase: codefresh
  postgresUser: postgres
  postgresPassword: eC9arYka4ZbH
  resources:
    requests:
      memory: 128Mi

mongodb:
  image: bitnami/mongodb:3.4.6-r0
  mongodbRootPassword: XT9nmM8dZD
  resources:
    requests:
      memory: 64Mi

redis:
  redisPassword: hoC9szf7NtrU
  resources:
    requests:
      memory: 64Mi

rabbitmq:
  rabbitmqUsername: user
  rabbitmqPassword: cVz9ZdJKYm7u

registry:
  mainChart: codefresh
  storageSize: 4Gi

builder:
  replicaCount: 1

runtime_envs:
  - name: codefresh-inc
    inCluster: true
    selectorRuntimeEnv: codefresh-inc
    namespace: dinds

cfui:
  image: gcr.io/codefresh-enterprise/cf-ui
  imageTag: onprem-v167

cfapi:
  image: gcr.io/codefresh-enterprise/cf-api
  imageTag: onprem-v169
  mongodbImage: bitnami/mongodb:3.4.6-r0
  env:
    ON_PREMISE: true
    LOGGER_LEVEL: debug

cfruntime:
  image: gcr.io/codefresh-enterprise/cf-runtime
  imageTag: onprem-v111

global:
  #appUrl: app-url
  githubInternalToken: placeholder
  githubClientSecret: placeholder
  githubClientID: placeholder

  gitlabClientID: placeholder
  gitlabClientSecret: placeholder

  bitbucketClientID: invalid-id
  bitbucketClientSecret: invalid-secret

  # Global codefresh chart name; all subcharts use this name to access secrets and configmaps
  codefresh: codefresh

  # default application protocol
  appProtocol: http

  # Codefresh Payments service
  paymentsService: payments

  # cfapi service name
  cfapiService: cfapi

  # cfapi internal service port
  cfapiInternalPort: 3000

  # Builder service
  builderService: builder

  # Runner service
  runnerService: runner

  # dind image with tag
  dindImage: docker:17.05-dind

  # dind cpu requests
  dindCPU: 100m

  # dind memory requests
  dindMemory: 256Mi

  # dind cpu limits
  dindCPULimits: 1000m

  # dind memory limits
  dindMemoryLimits: 4096Mi

  # tls-sign service
  tlsSignService: cfsign
  tlsSignPort: 4999

  # nats service
  natsService: nats
  natsPort: 4222

  # rabbitmq service name
  rabbitService: rabbitmq

  # mongodb service
  mongoService: mongodb
  mongoPort: 27017
  mongodbDatabase: codefresh
  mongodbPassword: mTiXcU2wafr9
  mongodbUsername: cfuser

  # consul service
  consulService: consul

  # consul http port
  consulHttpPort: 8500

  # Redis service
  redisService: redis

  # Docker Registry service
  registryService: registry

  # registry port
  registryPort: 5000

  # PostgresSQL service
  postgresService: postgresql

  # database
  postgresDatabase: codefresh

tags:
  saas: false

