---
# on-prem values
imagePullPolicy: IfNotPresent

dockercfg: placeholder

# default service port
servicePort: 80

# image with kubectl that can work with our K8s version
kubectlImage: quay.io/codefresh/generate-certs:1.0.0

slackAppID: "4027524866.65820083427"
slackAppSecret: placeholder

stripeSecretKey: sk_test_8AnaAlccXXkcPXP7vrgKZQyy
stripePublicKey: ""
stripeWebhookSecret: ""

rollbarAccessToken: ""

logglyToken: invalid-token

firebaseUrl: "https://codefresh-on-prem.firebaseio.com/on-prem"
firebaseSecret: placeholder

rbacEnable: true
rbacCreate: true
#webTLS:
#  secretName: star.codefresh.io

ingress:
  enabled: true
  rbacEnable: true
#  domain: '*'
#  webTlsSecretName: "star.codefresh.io"

# ingress resource annotations:
  annotations:
    kubernetes.io/ingress.class: nginx-codefresh
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/redirect-to-https: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
          more_set_headers "X-Request-ID: $request_id";
          proxy_set_header X-Request-ID $request_id;

consul:
  DatacenterName: codefresh-onprem
  Replicas: 1
  Memory: 64Mi
  nodeSelector: {}


postgresql:
  postgresDatabase: codefresh
  postgresUser: postgres
  postgresPassword: eC9arYka4ZbH
  cleanJob:
    enabled: true
  nodeSelector: {}
  resources:
    requests:
      memory: 128Mi

mongodb:
  image: bitnami/mongodb:4.2
  mongodbRootPassword: XT9nmM8dZD
  # version: "4.2" # default tag; overrides tag in `mongodb.image` field
  migration:
    setFeatureCompat: "3.6"
  nodeSelector: {}
  resources:
    requests:
      memory: 64Mi

redis:
  redisPassword: hoC9szf7NtrU
  nodeSelector: {}
  resources:
    requests:
      memory: 64Mi

rabbitmq:
  rabbitmqUsername: user
  rabbitmqPassword: cVz9ZdJKYm7u
  nodeSelector: {}

registry:
  mainChart: codefresh
  nodeSelector: {}

builder:
  replicaCount: 1

getRuntimeEnvs: files/on-prem/runtimeEnvironments.json
mongoSeedJobScript: files/on-prem/mongoSeedJobScript
postgresSeedJobScript: files/on-prem/postgresSeedScript
postgresCleanJobScript: files/on-prem/postgresCleanJobScript
updateDefREImgScript: files/on-prem/updateDefREImgScript
migrateHermesDataScript: files/on-prem/migrateHermesDataScript
setMdbCompatVerScript: files/on-prem/setMdbCompatVerScript

runtime_envs:
  - name: codefresh-inc
    inCluster: true
    selectorRuntimeEnv: codefresh-inc
    namespace: dinds

nomios:
  image:
    name: codefresh/nomios
    dockerRegistry: gcr.io/codefresh-enterprise/

cronus:
  event:
    action: "s"
  image:
    name: codefresh/cronus
    dockerRegistry: gcr.io/codefresh-enterprise/

hermes:
  image:
    name: codefresh/hermes
    dockerRegistry: gcr.io/codefresh-enterprise/
  redis:
    enabled: false # deprecation of a separate redis for hermes (CR-705)
    redisPassword: kj57kfwjeg
    db: 15

cfui:
  image: codefresh/cf-ui
  dockerRegistry: gcr.io/codefresh-enterprise/
  dockercfg: placeholder
  logglyToken: invalid-token
  segmentKey: invalid-key
  newrelicLicenseKey: invalid-key
  env:
    ON_PREMISE: true
#  webTLS:
#    secretName: star.codefresh.io

onboarding-status:
  enabled: false
  image: gcr.io/codefresh-enterprise/codefresh/onboarding-status
  dockercfg: placeholder
  newrelicLicenseKey: invalid-key

runtime-environment-manager:
  enabled: true
  dockerRegistry: gcr.io/codefresh-enterprise/
  image: codefresh/runtime-environment-manager
  dockercfg: placeholder
  newrelicLicenseKey: invalid-key
  env:
    ON_PREMISE: true

cfanalytic:
  dockerRegistry: gcr.io/codefresh-enterprise/
  image: codefresh/cf-analytic
  enabled: false

cfapi:
  github:
    apiPathPrefix: /api/v3
  image: codefresh/cf-api
  dockerRegistry: gcr.io/codefresh-enterprise/
  expirationURL: https://codefresh.io/contact-sales
  rbacEnable: true
  env:
    ON_PREMISE: true
    AUDIT_AUTO_CREATE_DB: true
    LOGGER_LEVEL: debug
    RUNTIME_MONGO_DB: codefresh
  deploymentTemplateImages: |
    [
      {
        "image": "codefresh/remote-docker:latest",
        "description": "Deploy image to Swarm",
        "link": "https://docs.codefresh.io/docs/docker-swarm",
        "code": " # Required Environment Variables:\n #\n # SSH_KEY - private SSH key, used to access Docker swarm master machine.\n #           need to replace 'newline' character with SPLIT_CHAR character.\n # SPLIT_CHAR - split character, you've used to replace newline in SSH key. Recommendation: use ',' (comma character).\n #\n # Swarm delpoy command arguments:\n #\n # RDOCKER_HOST - remote Docker swarm master machine, accessible over SSH (for example, ubuntu@ec2-public-ip)\n # STACK_NAME - is new Docker stack name\n #\n # Use command below to deploy compose application to a Swarm cluster\n # rdocker ${{RDOCKER_HOST}} docker stack deploy --compose-file docker-stack.yml ${{STACK_NAME}}\n #\n # read more here: https://docs.codefresh.io/docs/docker-swarm"
      },
      {
        "image": "codefresh/cf-deploy-ecs:latest",
        "description": "Deploy image to ECS",
        "link": "https://docs.codefresh.io/docs/amazon-ecs",
        "code": " # Required Environment Variables:\n #\n # AWS_ACCESS_KEY_ID - AWS access key\n # AWS_SECRET_ACCESS_KEY - AWS secret access key\n #\n # ECS deploy command arguments:\n #\n # AWS_REGION - target AWS region\n # CLUSTER_NAME - ECS cluster name\n # SERVICE_NAME - ECS service names\n #\n # Use command below to deploy application to AWS ECS\n \n # cfecs-update ${{AWS_REGION}} ${{CLUSTER_NAME}} ${{SERVICE_NAME}}\n #\n # read more here: https://docs.codefresh.io/docs/amazon-ecs"
      },
      {
        "image": "codefresh/cf-deploy-kubernetes:latest",
        "description": "Deploy image to Kubernetes",
        "link": "https://docs.codefresh.io/docs/kubernetes",
        "code": " # Required Environment Variables:\n #\n # KUBERNETES_USER - The user for the Kubernetes cluster.\n # KUBERNETES_PASSWORD - The password for the Kubernetes cluster.\n # KUBERNETES_SERVER - The server (HTTPS endpoint) of the Kubernetes cluster's API\n #\n # Use command below to deploy compose application to kubernetes\n #\n # /cf-deploy-kubernetes deployment.yml\n #\n # Make sure you change the path of 'deployment.yml' to the path in your repository\n #\n # read more about how to obtain the kubernetes credentials and using the codefresh deploy here: https://docs.codefresh.io/docs/kubernetes\n"
      }
    ]

cfapi-buildmanager:
  replicaCount: 0
cfapi-cacheevictmanager:
  replicaCount: 0
cfapi-downloadlogmanager:
  replicaCount: 0
cfapi-endpoints:
  replicaCount: 0
cfapi-eventsmanagersubscriptions:
  replicaCount: 0
cfapi-terminators:
  replicaCount: 0
k8s-monitor:
  image: codefresh/cf-k8s-monitor
  enabled: true
  replicaCount: 0
  dockerRegistry: gcr.io/codefresh-enterprise/

cluster-providers:
  replicaCount: 1
  gcAuthClientID: ""
  gcAuthClientSecret: ""
  safeSecret: ""
  image: codefresh/cluster-providers
  dockerRegistry: gcr.io/codefresh-enterprise/

cfsign:
  replicaCount: 1
  image: codefresh/cf-tls-sign
  dockerRegistry: gcr.io/codefresh-enterprise/

charts-manager:
  replicaCount: 1
  image: codefresh/charts-manager
  dockerRegistry: gcr.io/codefresh-enterprise/
  environment:
    MONGO_URI: mongodb://mongodb:27017/charts-manager
    POSTGRES_HOST: cf-postgresql
    EVENTBUS_URI: amqp://cf-rabbitmq
    CONTEXT_MANAGER_URI: cf-context-manager
    API_URI: cf-cfapi
  disablePublicRepos: true

context-manager:
  safeSecret: ""
  replicaCount: 1
  image: codefresh/context-manager
  dockerRegistry: gcr.io/codefresh-enterprise/
  environment:
    MONGO_URI: mongodb://mongodb:27017/context-manager
    EVENTBUS_URI: amqp://cf-rabbitmq
    POSTGRES_HOST: cf-postgresql

pipeline-manager:
  replicaCount: 1
  safeSecret: ""
  stepsCatalogGithubToken: ""
  image: codefresh/pipeline-manager
  dockerRegistry: gcr.io/codefresh-enterprise/
  environment:
    MONGO_URI: mongodb://mongodb:27017/pipeline-manager
    INTERNAL_API_URI: http://cf-cfapi:9007

gitops-dashboard-manager:
  imagePullPolicy: IfNotPresent
  image: codefresh/gitops-dashboard-manager
  dockerRegistry: gcr.io/codefresh-enterprise/
  env:
    LOGGER_LEVEL: "info"
    EVENTBUS_IGNORE_CREATE_SCHEMA: true
    INTERNAL_API_URI: http://cf-cfapi:9007

kube-integration:
  replicaCount: 1
  image: codefresh/kube-integration
  dockerRegistry: gcr.io/codefresh-enterprise/

tasker-kubernetes:
  replicaCount: 1
  image: codefresh/tasker-kubernetes
  dockerRegistry: gcr.io/codefresh-enterprise/

helm-repo-manager:
  replicaCount: 1
  image:
    name: codefresh/helm-repo-manager
    dockerRegistry: gcr.io/codefresh-enterprise/

cf-broadcaster:
  replicaCount: 1
  image: codefresh/cf-broadcaster
  dockerRegistry: gcr.io/codefresh-enterprise/
  env:
    RUNTIME_MONGO_DB: codefresh

chartmuseum:
  publicHelmRepo: false
  localHelmRepo: true
  ingress:
    enabled: false
    # Used to create an Ingress record.
    hosts:
      - chartmuseum.local
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
  env:
    open:
      STORAGE: local
      DEPTH: 2
      DEBUG: "true"
      ALLOW_OVERWRITE: "true"
      DISABLE_API: "false"
      DISABLE_METRICS: "false"
      INDEX_LIMIT: 2500

global:
  # Instantiate databases with seed data. Usually used in dynamic and on-prem environments.
  #seedJobs: true
  #certsJobs: true

  # when using custom registry, enable the following seetings to add imagePullSecret to all images and replace docker registry prefix with custom one (has to be with trailing /)
  #privateRegistry: true
  #dockerRegistry: containers-nexus-francisco.codefresh.io/

  stepsCatalogOnPremise: "1"
  #appUrl: app-url
  githubInternalToken: placeholder
  githubClientSecret: placeholder
  githubClientID: placeholder

  gitlabClientID: placeholder
  gitlabClientSecret: placeholder

  bitbucketClientID: invalid-id
  bitbucketClientSecret: invalid-secret

  # Global codefresh chart name; all subcharts use this name to access secrets and configmaps
  codefresh: codefresh

  # default application protocol
  appProtocol: http

  # Codefresh Payments service
  paymentsService: payments
  paymentsServicePort: 9000

  # cfapi service name
  cfapiService: cfapi
  cfcrDomain: ""
  gceProject: ""
  # cfapi internal service port
  cfapiInternalPort: 3000

  # Builder service
  builderService: builder

  # Runner service
  runnerService: runner

  # dind image with tag
  #dindImage: docker:17.06-dind
  dindImage: docker:18.09-dind
  #dindImage: eugenecodefresh/cf-dind-with-cleaner:17.05.0-ce-dind

  # curl image
  curlImage: quay.io/codefresh/curl:1.0.0

  # dind cpu requests
  dindCPU: 100m

  # dind memory requests
  dindMemory: 256Mi

  # dind cpu limits
  dindCPULimits: 1000m

  # dind memory limits
  dindMemoryLimits: 4096Mi

  # tls-sign service
  tlsSignService: cfsign
  tlsSignPort: 4999

  # nats service
  natsService: nats
  natsPort: 4222

  # rabbitmq service name
  rabbitService: rabbitmq

  # mongodb service
  mongoURI: "mongodb://cfuser:mTiXcU2wafr9@mongodb:27017"
  mongoService: mongodb
  mongoPort: 27017
  mongodbDatabase: codefresh
  mongodbPassword: mTiXcU2wafr9
  mongodbUsername: cfuser
  mongodbImage: bitnami/mongodb:4.2
  mongodbRootUser: root
  mongodbRootPassword: XT9nmM8dZD

  # consul service
  consulService: consul

  # consul http port
  consulHttpPort: 8500

  # Redis service
  redisService: redis

  # [Deprecated] Docker Registry service
  registryService: registry

  # [Deprecated] Docker Registry port
  registryPort: 5000

  # PostgresSQL service
  postgresService: postgresql

  # PostgresSQL user name
  postgresUser: postgres
  # PostgresSQL password
  postgresPassword: eC9arYka4ZbH

  # database
  postgresDatabase: codefresh

  # k8s-beta
  clusterProvidersService: cluster-providers
  clusterProvidersPort: 9000
  kubeIntegrationService: kube-integration
  kubeIntegrationPort: 9000
  accountsReferralsService: accounts-referrals
  accountsReferralsPort: 9000
  chartsManagerService: charts-manager
  chartsManagerPort: 9000
  contextManagerService: context-manager
  contextManagerPort: 9000
  pipelineManagerService: pipeline-manager
  pipelineManagerPort: 9000
  gitopsDashboardManagerService: gitops-dashboard-manager
  gitopsDashboardManagerDatabase: pipeline-manager
  gitopsDashboardManagerPort: 9000
  onboardingStatusService: onboarding-status
  onboardingStatusPort: 80
  runtimeEnvironmentManagerService: runtime-environment-manager
  runtimeEnvironmentManagerPort: 80
  helmRepoManagerService: helm-repo-manager
  hermesService: hermes
  dindProviderService: dind-provider
  dindProviderPort: 9000
  broadcasterService: cf-broadcaster
  broadcasterPort: 80
  cfk8smonitorService: k8s-monitor
  onprem: true
  ### new logging solution
  runtimeRedisHost: cf-redis
  runtimeRedisPassword: hoC9szf7NtrU
  runtimeRedisDb: "1"
  runtimeRedisPort: "6379"
  runtimeMongoURI: mongodb://cfuser:mTiXcU2wafr9@mongodb:27017
  runtimeMongoDb: codefresh
  ### new logging solution


  internalServiceTolerations:
  - effect: NoSchedule
    key: nodeType
    operator: Equal
    value: internal

cf-db:
  enabled: true
  rabbit:
    enabled: true

tags:
  saas: false
  infra: true
  old-scheduler: false
  deprecated: false
engineImage: codefresh/engine:1.131.6
CONTAINER_LOGGER_IMAGE: codefresh/cf-container-logger:1.4.4
GIT_CLONE_IMAGE: codefresh/cf-git-cloner:10.0.2
DOCKER_PUSHER_IMAGE: codefresh/cf-docker-pusher:6.0.3-os
DOCKER_TAG_PUSHER_IMAGE: codefresh/cf-docker-tag-pusher:v2
DOCKER_PULLER_IMAGE: codefresh/cf-docker-puller:8.0.2
DOCKER_BUILDER_IMAGE: codefresh/cf-docker-builder:1.1.12
COMPOSE_IMAGE: codefresh/compose:1.25.0-1.1.1
KUBE_DEPLOY: codefresh/cf-deploy-kubernetes:16.1.4
FS_OPS_IMAGE: codefresh/fs-ops:1.1.1
TEMPLATE_ENGINE: codefresh/pikolo:latest

# versions:
