mongodb:
  fullnameOverride: mongodb
  auth:
    rootPassword: XT9nmM8dZD

postgresql:
  fullnameOverride: postgresql
  auth:
    password: eC9arYka4ZbH

redis:
  fullnameOverride: redis
  config:
    requirepass: hoC9szf7NtrU
