## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# number of Nats replicas
# by default 1
# replicaCount: 1

# image name
image: gcr.io/codefresh-enterprise/cf-api

# imagre tag  
imageTag: onprem-v116

# application URL
appUrl: https://codefresh.local

# port 
port: 80

# target port
targetPort: 80

# readiness port
readinessPort: 80

# mongodb service name to use
mongodbService: mongodb

# defualt mongo image to use for mongoimport
mongoImage: mongo:3.4

# mongodb user; default empty
# mongodbUsername:

# mongodb password; default empty
# mongodbPassword:

# mongodb database; local by default
mongodbDatabase: local

# consul service
consulService: consul

# nats service
natsService: nats

# nats service port
natsServicePort: 4222

# RMQ service
rabbitmqService: rabbitmq
# RabbitMQ user; default user
rabbitmqUsername: user

# RabbitMQ password; default empty
# rabbitmqPassword:

# PostresSQL service name
postgresService: postresql
# PostresSQL database
postgresDatabase: postgres
# PostresSQL user
postgresUser: postgres

# Redis service
redisService: redis

# GitHub configuration
github:
  apiHost: api.github.com
  apiPathPrefix: /api/v3
  loginHost: github.com
  protocol: https

# GitHub client ID
# githubClientID:

# GitHub Client Secret key
# githubClientSecret:

gitlab:
  loginHost: gitlab.com
  protocol: https

# GitLab Client ID
# gitlabClientID:

# GitLab Cleint Secret key
# gitlabClientSecret

# API Safe Secret
# apiSafeSecret: 

# Stripe secret key
# stripeSecretKey: 

# Firebase secret
# firebaseSecret: 

# Slack APP ID
# slackAppID: 

# ENV
env:
  APP_ENV: staging
  NODE_ENV: kubernetes
  PORT: 80
  PROTOCOL: https
  DOCKER_NODE_PUBLIC_DOMAIN: cf-cd.com
  DOCKER_NODE_CERT_PATH: /etc/ssl/cf
  PROVIDERS_JSON_PATH: /etc/admin/providers.json
  TLS_SIGN_CLIENT_KEY: sdf
  NEWRELIC_LICENSE_KEY: abc
  FIREBASE_URL: https://codefresh-on-prem.firebaseio.com/on-prem=
  OAUTH_ROUTER_CALLBACK:
  BITBUCKET_CLIENT_ID: aaa
  BITBUCKET_CLIENT_SECRET: aaa
  SEGMENT_KEY: asd
  SLACK_INTERNAL: adsfa
  SLACK_APP_SECRET: asdfa
  LOGGLY_TOKEN: asdf
  SEGMENT_ACTIVE: false
  MAIL_ACTIVE: false
  LOGS_PATH: /var/log/cf-api.log
  LOGGER_LEVEL: error
  LOGGER_MORAN_ACTIVE: false
  PROGRESS_BUILDLOGS_BUCKETNAME: progress-logs-staging
  INTERNAL_USE_GITHUB_ACCESS_TOKEN: asdf