imagePullPolicy: Always

# Number of replicas
replicaCount: 1
redeploy: false

image: r.cfcr.io/codefresh-inc/codefresh/pipeline-manager
imageTag: master

# Service type (ClusterIP, NodePort, LoadBalancer)
#serviceType: ClusterIP

# Service port
port: 9000

# Pod (target) port
targetPort: 9000

# service database name
mongodbName: pipeline-manager

mongoCreateDbJobScript: files/mongoCreateDbJobScript

# formatLogsToElk logs will be formatter as elk expect to read it
formatLogsToElk: true