---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
spec:
  tls:
    - secretName: star.codefresh.io
  backend:
    serviceName: production-cfui
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /api/*
        backend:
          serviceName: production-cfapi
          servicePort: 80

