---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  revisionHistoryLimit: 50
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      {{- if .Values.redeploy }}
      annotations:
        forceRedeployUniqId: {{ now | quote }}
      {{- end }}
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Values.imageTag | quote }}
    spec:
      affinity:
{{ toYaml (default .Values.global.appServiceAffinity .Values.affinity) | indent 8 }}
      imagePullSecrets:
        - name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-registry"
      containers:
      - name: {{ template "fullname" . }}
        {{- if .Values.global.onprem }}
        image: gcr.io/codefresh-enterprise/codefresh/cf-tls-sign:v2
        {{- else }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        {{- end }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        volumeMounts:
        {{- if .Values.global.onprem }}
        - mountPath: /cacerts/cf-ca.pem
          name: cf-ca
          subPath: ca.pem
        - mountPath: /cacerts/cf-ca-key.pem
          name: cf-ca
          subPath: ca-key.pem
        {{- else }}
        - mountPath: /cacerts
          name: cf-ca
        {{- end }}
        - mountPath: /certs
          name: certs-data
      restartPolicy: Always
      volumes:
      - name: cf-ca
        secret:
        {{- if .Values.global.onprem }}
          secretName: cf-codefresh-certs-client
        {{- else }}
          secretName: {{ template "fullname" . }}
        {{- end }}
      - name: certs-data
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}