{{ $name := printf "%v-%v-%v" .Release.Name .Values.global.codefresh "registry" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
data:
  internal-registry.json: |
    {}
  additional-internal-registries.json: |
    []