apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  # app url
  app-url: {{ .Values.appUrl }}

  # default application protocol: http or https
  app-protocol: {{ .Values.appProtocol }}

  # mongodb service name to use
  mongodb-service: mongodb
  # mongodb database; local by default
  mongodb-database: {{ .Values.mongodb.mongodbDatabase }}
  # mongodb port
  mongodb-port: "27017"

  # consul service
  consul-service: consul

  # nats service
  nats-service: nats
  # nats service port
  nats-port: "4222"

  # RMQ service
  rabbitmq-service: rabbitmq

  # PostresSQL service name
  postgres-service: postgresql
  # PostresSQL database
  postgres-database: {{ .Values.postgresql.postgresDatabase }}

  # Redis service
  redis-service: redis

  # Docker registry service
  registry-service: registry

  # Firebase url
  firebase-url: https://codefresh-on-prem.firebaseio.com/on-prem