{{- $ingressName := printf "%s-ingress" (include "codefresh.fullname" .) }}
{{- if and (hasKey .Values.ingress "nameOverride") .Values.ingress.nameOverride }}
  {{- $ingressName = .Values.ingress.nameOverride }}
{{- end }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default (index .Values "ingress-nginx" "controller" "ingressClassResource" "name") }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.global.appUrl }}
      secretName: {{ include "codefresh.ingress.tlsSecretName" . }}
  {{- end }}
  defaultBackend:
    service:
      name: {{ printf "%s-%s" .Release.Name (index .Subcharts "cfui" ).Chart.Name }}
      port:
        number: {{ (index .Subcharts "cfui" ).Values.service.main.ports.http.port }}
  rules:
  - host: {{ .Values.ingress.domain | default .Values.global.appUrl }}
    http:
      paths:
      {{- range $serviceName, $paths := .Values.ingress.services }}
      {{- if and (index $.Subcharts $serviceName) }}
        {{- range $path := $paths }}
      - path: {{ $path }}
        pathType: ImplementationSpecific
        backend:
          service:
            {{- $fullServiceName := (index $.Subcharts $serviceName).Values.fullnameOverride }}
            {{- if $fullServiceName }}
            name: {{ $fullServiceName }}
            {{- else }}
            name: {{ printf "%s-%s" $.Release.Name (index $.Subcharts $serviceName ).Chart.Name }}
            {{- end }}
            port:
              number: {{ (index $.Subcharts $serviceName ).Values.service.main.ports.http.port }}
        {{- end }}
      {{- end }}
      {{- end }}
{{- end}}
