{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if .Values.global.exposeRegistry }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    {{- end }}
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  tls:
    - hosts:
      - '{{ .Values.ingress.domain | default .Values.global.appUrl }}'
      {{- if .Values.webTLS }}
      secretName: {{ template "fullname" . }}-{{ .Values.webTLS.secretName }}
      {{- else }}
      secretName: {{ template "fullname" . }}-star-selfsigned
      {{- end }}
  backend:
    serviceName: {{ .Release.Name }}-cfui
    servicePort: {{ .Values.servicePort }}
  rules:
  - host: {{ .Values.ingress.domain | default .Values.global.appUrl }}
    http:
      paths:
      - path: /api/
        backend:
          serviceName: {{ .Release.Name }}-cfapi
          servicePort: {{ .Values.servicePort }}
      - path: /ws
        backend:
          serviceName: {{ .Release.Name }}-cfapi
          servicePort: {{ .Values.servicePort }}
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-cfui
          servicePort: {{ .Values.servicePort }}
      {{- if .Values.global.exposeRegistry }}
      - path: /v2/
        backend:
          serviceName: {{ .Release.Name }}-registry
          servicePort: 5000
      {{- end }}
{{- end }}