apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if .Values.global.exposeRegistry }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    {{- end }}
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  tls:
    - hosts:
      - '{{ .Values.ingress.domain | default .Values.global.appUrl }}'
      {{- if .Values.webTLS }}
      secretName: {{ template "fullname" . }}-{{ .Values.webTLS.secretName }}
      {{- else }}
      secretName: {{ template "fullname" . }}-star-selfsigned
      {{- end }}
  defaultBackend:
    service:
      name: {{ .Release.Name }}-cfui
      port:
        number: {{ .Values.servicePort }}
  ingressClassName: {{ .Values.ingress.ingressClassName | default (index .Values "ingress-nginx" "controller" "ingressClassResource" "name") }}
  rules:
  - host: {{ .Values.ingress.domain | default .Values.global.appUrl }}
    http:
      paths:
      - path: /api/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi
            port:
              number: {{ .Values.servicePort }}
      - path: /ws
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi
            port:
              number: {{ .Values.servicePort }}
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfui
            port:
              number: {{ .Values.servicePort }}
      {{- if .Values.global.exposeRegistry }}
      - path: /v2/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-registry
            port:
              number: 5000
      {{- end }}