{{- if and .Values.ingress.enabled (index .Values "k8s-monitor" "enabled") }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-k8s-monitor
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: "15m"
spec:
  rules:
    - host: {{ .Values.ingress.domain | default .Values.global.appUrl }}
      http:
        paths:
        - path: /api/k8s-monitor/
          backend:
            serviceName: {{ .Release.Name }}-k8s-monitor
            servicePort: {{ index .Values "k8s-monitor" "port" }}
  tls:
    - hosts:
      - '{{ .Values.ingress.domain | default .Values.global.appUrl }}'
      {{- if .Values.webTLS }}
      secretName: {{ template "fullname" . }}-{{ .Values.webTLS.secretName }}
      {{- else }}
      secretName: {{ template "fullname" . }}-star-selfsigned
      {{- end }}
{{- end }}