{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  tls:
    - hosts:
      - '{{ .Values.ingress.domain | default .Values.global.appUrl }}'
      {{- if .Values.webTLS }}
      secretName: {{ template "fullname" . }}-{{ .Values.webTLS.secretName }}
      {{- else }}
      secretName: {{ template "fullname" . }}-star-selfsigned
      {{- end }}
  defaultBackend:
    service:
      name: {{ .Release.Name }}-cfui
      port:
        number: {{ .Values.ingress.servicePort }}
  ingressClassName: {{ .Values.ingress.ingressClassName | default (index .Values "ingress-nginx" "controller" "ingressClassResource" "name") }}
  rules:
  - host: {{ .Values.ingress.domain | default .Values.global.appUrl }}
    http:
      paths:
      {{- if .Values.cfapi.enabled }}
      - path: /api/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /ws
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi
            port:
              number: {{ .Values.ingress.servicePort }}
      {{- else if and (eq .Values.global.cfapiService "cfapi-internal") (index .Values "cfapi-endpoints" "enabled") (index .Values "cfapi-internal" "enabled") }}
      - path: /api/progress/download
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-downloadlogmanager
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/public/progress/download
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-downloadlogmanager
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-endpoints
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/admin/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-admin
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /ws
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-ws
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/environments-v2/argo/events
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-environments
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/gitops/resources
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-gitops-resource-receiver
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/gitops/rollout
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-gitops-resource-receiver
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/k8s-monitor/
        pathType: ImplementationSpecific
        backend:
            service:
              name: {{ .Release.Name }}-cfapi-kubernetesresourcemonitor
              port:
                number: {{ .Values.ingress.servicePort }}
      - path: /api/team
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-teams
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/kubernetes
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-kubernetes-endpoints
            port:
              number: {{ .Values.ingress.servicePort }}
      - path: /api/testReporting
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfapi-test-reporting
            port:
              number: {{ .Values.ingress.servicePort }}
      {{- end }}
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-cfui
            port:
              number: {{ .Values.ingress.servicePort }}
{{- end}}