apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/redirect-to-https: "false"
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  tls:
    - secretName: {{ template "fullname" . }}-star-selfsigned
  backend:
    serviceName: {{ .Release.Name }}-cfui
    servicePort: {{ .Values.servicePort }}
  rules:
  - http:
      paths:
      - path: /api/
        backend:
          serviceName: {{ .Release.Name }}-cfapi
          servicePort: {{ .Values.servicePort }}
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-cfui
          servicePort: {{ .Values.servicePort }}
