apiVersion: v2
description: Helm Chart for Codefresh On-Prem
name: codefresh
version: 0.0.0
keywords:
  - codefresh
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
sources:
  - https://github.com/codefresh-io/codefresh-onprem-helm
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
appVersion: 0.0.0
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/alternativeName: "codefresh-onprem"
  artifacthub.io/containsSecurityUpdates: "true"
  # supported kinds are added, changed, deprecated, removed, fixed and security.
  # artifacthub.io/changes: |
  #   - kind:
  #     description: ""
  artifacthub.io/changes: "- kind: added\n  description: 'Add support for API keys IP allowlist. Early access.'\n- kind: changed\n  description: 'update \"cfapi\" to 22.8.7-onprem-13bae1c'\n- kind: changed\n  description: 'update \"cfui\" to 14.100.20-onprem-f7d5126'      \n- kind: changed\n  description: 'update \"argo-platform\" to 1.4119.0-onprem-502b2fe'      \n- kind: security\n  description: 'Update \"cf-platform-analytics\" to 0.54.8. Fix various security vulnerabilities'\n- kind: security\n  description: 'Update hermes up to 0.22.12. Fix various security vulnerabilities'\n- kind: security\n  description: 'Update nomios up to 0.12.3. Fix various security vulnerabilities'\n- kind: security\n  description: 'Update cronus up to 0.9.5. Fix various security vulnerabilities'\n- kind: security\n  description: 'Update helm-repo-manager up to 0.23.7. Fix various security vulnerabilities'\n"
dependencies:
  - name: cf-common
    repository: oci://quay.io/codefresh/charts
    version: 0.18.1
  - name: internal-gateway
    repository: oci://quay.io/codefresh/charts
    version: 0.12.3
    condition: internal-gateway.enabled
  - name: consul
    version: 11.4.32
    repository: https://charts.bitnami.com/bitnami
    condition: consul.enabled
  - name: mongodb
    version: 15.6.26
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled,mongo.enabled,global.mongoDeploy
  - name: postgresql
    version: 16.7.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: postgresql-ha
    version: 12.0.4
    repository: oci://quay.io/codefresh/charts
    condition: postgresql-ha.enabled
  - name: redis
    version: 20.13.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: redis-ha
    repository: https://dandydeveloper.github.io/charts
    version: 4.26.1
    condition: redis-ha.enabled
  - name: rabbitmq
    version: 15.5.3
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: nats
    version: 9.0.28
    repository: https://charts.bitnami.com/bitnami
    condition: nats.enabled
  - name: builder
    repository: oci://quay.io/codefresh/charts
    condition: builder.enabled
    version: 2.0.0
  - name: ingress-nginx
    version: 4.14.3
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: cluster-providers
    version: 1.20.4
    repository: oci://quay.io/codefresh/charts
    condition: cluster-providers.enabled
    tags:
      - cf-internal
  - name: kube-integration
    version: 2.1.5
    repository: oci://quay.io/codefresh/charts
    condition: kube-integration.enabled
    tags:
      - cf-internal
  - name: charts-manager
    version: 1.28.8
    repository: oci://quay.io/codefresh/charts
    condition: charts-manager.enabled
    tags:
      - cf-internal
  - name: cfsign
    version: 1.8.22
    repository: oci://quay.io/codefresh/charts
    condition: cfsign.enabled
    tags:
      - cf-internal
  - name: tasker-kubernetes
    version: 1.29.3
    repository: oci://quay.io/codefresh/charts
    condition: tasker-kubernetes.enabled
    tags:
      - cf-internal
  - name: context-manager
    version: 2.41.10
    repository: oci://quay.io/codefresh/charts
    condition: context-manager.enabled
    tags:
      - cf-internal
  - name: pipeline-manager
    version: 4.2.6
    repository: oci://quay.io/codefresh/charts
    condition: pipeline-manager.enabled
    tags:
      - cf-internal
  - name: gitops-dashboard-manager
    version: 1.16.14
    repository: oci://quay.io/codefresh/charts
    condition: gitops-dashboard-manager.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-auth
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-auth.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-internal
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-internal.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-ws
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-ws.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-admin
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-admin.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-endpoints
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-endpoints.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-terminators
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-terminators.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-sso-group-synchronizer
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-sso-group-synchronizer.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-buildmanager
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-buildmanager.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-cacheevictmanager
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-cacheevictmanager.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-eventsmanagersubscriptions
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-eventsmanagersubscriptions.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-kubernetesresourcemonitor
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-kubernetesresourcemonitor.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-environments
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-environments.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-gitops-resource-receiver
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-gitops-resource-receiver.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-downloadlogmanager
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-downloadlogmanager.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-teams
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-teams.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-kubernetes-endpoints
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-kubernetes-endpoints.enabled
    tags:
      - cf-internal
  - name: cfapi
    alias: cfapi-test-reporting
    version: 22.11.1
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-test-reporting.enabled
    tags:
      - cf-internal
  - name: cfui
    version: 14.100.29
    repository: oci://quay.io/codefresh/charts
    condition: cfui.enabled
    tags:
      - cf-internal
  - name: k8s-monitor
    version: 4.12.3
    repository: oci://quay.io/codefresh/charts
    condition: k8s-monitor.enabled
    tags:
      - cf-internal
  - name: runtime-environment-manager
    version: 4.1.8
    repository: oci://quay.io/codefresh/charts
    condition: runtime-environment-manager.enabled
    tags:
      - cf-internal
  - name: cf-broadcaster
    version: 1.15.13
    repository: oci://quay.io/codefresh/charts
    condition: cf-broadcaster.enabled
    tags:
      - cf-internal
  - name: helm-repo-manager
    version: 0.23.7
    repository: oci://quay.io/codefresh/charts
    condition: helm-repo-manager.enabled
    tags:
      - cf-internal
  - name: hermes
    version: 0.22.12
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
    tags:
      - cf-internal
  - name: nomios
    version: 0.12.3
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
    tags:
      - cf-internal
  - name: cronus
    version: 0.9.5
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
    tags:
      - cf-internal
  - name: cf-platform-analytics
    alias: cf-platform-analytics-platform
    version: 0.55.2
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
    tags:
      - cf-internal
  - name: cf-platform-analytics
    alias: cf-platform-analytics-etlstarter
    version: 0.55.2
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
    tags:
      - cf-internal
  - name: argo-platform
    version: 1.4125.0
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
    tags:
      - cf-internal
  - name: argo-hub-platform
    version: 0.1.43
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
    tags:
      - cf-internal
  - name: cf-oidc-provider
    repository: oci://quay.io/codefresh/charts
    version: 0.1.0
    condition: cf-oidc-provider.enabled
    tags:
      - cf-internal
