# kind: scheduler-kubernetes
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  type: {{ default "ClusterIP" .Values.serviceType | quote }}
  ports:
  - name: "dind-port"
    port: {{ .Values.containerPort }}
    protocol: TCP
  # *.dind.[namespace].svc.cluster.local
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}
