apiVersion: v2
description: Codefresh CD pipeline management platform for Kubernetes
name: codefresh
version: 1.2.13
kubeVersion: '>=1.19.0-0'
keywords:
- codefresh
- kubernetes
- pipeline
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
sources:
- https://github.com/codefresh-io/cf-helm
maintainers:
- name: Codefresh Authors
  email: dev@codefresh.io
appVersion: 1.2.0
dependencies:
- name: consul
  version: 1.1.3
  repository: file://pv-charts/consul
  condition: consul.enabled
  tags:
  - cf-infra
- name: mongodb
  version: 0.4.13
  repository: file://pv-charts/mongodb
  condition: mongo.enabled,global.mongoDeploy
  tags:
  - cf-infra
- name: postgresql
  version: 0.7.2
  repository: file://pv-charts/postgresql
  condition: postgresql.enabled
  tags:
  - cf-infra
- name: redis
  version: 16.13.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
  tags:
  - cf-infra
- name: rabbitmq
  version: 10.1.8
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
  tags:
  - cf-infra
- name: nats
  version: 0.1.2
  repository: file://../nats
  condition: nats.enabled
  tags:
  - cf-infra
- name: builder
  repository: https://chartmuseum.codefresh.io/builder
  condition: builder.enabled
  version: 1.0.0
  tags:
  - cf-infra
- name: runner
  repository: https://chartmuseum.codefresh.io/runner
  condition: runner.enabled
  version: 1.0.0
  tags:
  - cf-infra
- name: ingress-nginx
  version: 4.1.0
  repository: 'https://kubernetes.github.io/ingress-nginx'
  condition: ingress-nginx.enabled
  tags:
  - cf-infra
- name: cluster-providers
  version: "*"
  repository: https://chartmuseum.codefresh.io/cluster-providers
  tags:
  - cf-infra
- name: kube-integration
  version: "*"
  repository: https://chartmuseum.codefresh.io/kube-integration
  tags:
  - cf-infra
- name: charts-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/charts-manager
  tags:
  - cf-infra
- name: cfsign
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfsign
  condition: cfsign.enabled
  tags:
  - cf-infra
- name: tasker-kubernetes
  version: "*"
  repository: https://chartmuseum.codefresh.io/tasker-kubernetes
  tags:
  - cf-infra
- name: context-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/context-manager
  tags:
  - cf-infra
  - argo-platform
- name: pipeline-manager
  version: "3.121.12"
  repository: https://chartmuseum.codefresh.io/pipeline-manager
  tags:
  - cf-infra
- name: gitops-dashboard-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/gitops-dashboard-manager
  tags:
  - cf-infra
- name: cfapi
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi
  condition: cfapi.enabled
  tags:
  - cf-infra
- name: cfui
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfui
  condition: cfui.enabled
  tags:
  - cf-infra
- name: k8s-monitor
  version: "*"
  repository: https://chartmuseum.codefresh.io/k8s-monitor
  condition: k8s-monitor.enabled
  tags:
  - cf-infra
- name: runtime-environment-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/runtime-environment-manager
  condition: runtime-environment-manager.enabled
  tags:
  - cf-infra
- name: cf-broadcaster
  version: "*"
  repository: https://chartmuseum.codefresh.io/cf-broadcaster
  condition: cf-broadcaster.enabled
  tags:
  - cf-infra
- name: helm-repo-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/helm-repo-manager
  condition: helm-repo-manager.enabled
  tags:
  - cf-infra
- name: hermes
  version: "*"
  repository: https://chartmuseum.codefresh.io/hermes
  condition: hermes.enabled
  tags:
  - cf-infra
- name: nomios
  version: "*"
  repository: https://chartmuseum.codefresh.io/nomios
  condition: hermes.enabled
  tags:
  - cf-infra
- name: cronus
  version: "*"
  repository: https://chartmuseum.codefresh.io/cronus
  condition: hermes.enabled
  tags:
  - cf-infra
