apiVersion: v2
description: Codefresh CD pipeline management platform for Kubernetes
name: codefresh
version: 1.4.0
kubeVersion: '>=1.19.0-0'
keywords:
- codefresh
- kubernetes
- pipeline
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
sources:
- https://github.com/codefresh-io/cf-helm
maintainers:
- name: Codefresh Authors
  email: dev@codefresh.io
appVersion: 1.3.0
dependencies:
- name: consul
  version: 10.9.6
  repository: https://charts.bitnami.com/bitnami
  condition: consul.enabled
  tags:
  - cf-infra
- name: mongodb
  version: 13.6.2
  repository: https://charts.bitnami.com/bitnami
  condition: mongo.enabled,global.mongoDeploy,mongodb.enabled
  tags:
  - cf-infra
- name: postgresql
  version: 12.1.6
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
  tags:
  - cf-infra
- name: redis
  version: 17.3.14
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
  tags:
  - cf-infra
- name: rabbitmq
  version: 11.1.5
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
  tags:
  - cf-infra
- name: nats
  version: 7.4.8
  repository: https://charts.bitnami.com/bitnami
  condition: nats.enabled
  tags:
  - cf-infra
- name: builder
  repository: https://chartmuseum.codefresh.io/builder
  condition: builder.enabled
  version: 1.0.2
  tags:
  - cf-infra
- name: runner
  repository: https://chartmuseum.codefresh.io/runner
  condition: runner.enabled
  version: 1.0.0
  tags:
    - cf-infra
- name: ingress-nginx
  version: 4.3.0
  repository: 'https://kubernetes.github.io/ingress-nginx'
  condition: ingress-nginx.enabled
  tags:
  - cf-infra
- name: cluster-providers
  version: "*"
  repository: https://chartmuseum.codefresh.io/cluster-providers
  tags:
  - cf-infra
- name: kube-integration
  version: "*"
  repository: https://chartmuseum.codefresh.io/kube-integration
  tags:
  - cf-infra
- name: charts-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/charts-manager
  tags:
  - cf-infra
- name: cfsign
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfsign
  condition: cfsign.enabled
  tags:
  - cf-infra
- name: tasker-kubernetes
  version: "*"
  repository: https://chartmuseum.codefresh.io/tasker-kubernetes
  tags:
  - cf-infra
- name: context-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/context-manager
  tags:
  - cf-infra
- name: pipeline-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/pipeline-manager
  tags:
  - cf-infra
- name: gitops-dashboard-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/gitops-dashboard-manager
  tags:
  - cf-infra
- name: cfapi
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi
  condition: cfapi.enabled
  tags:
  - cf-infra
- name: cfapi-internal
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-internal
  condition: cfapi-internal.enabled
  tags:
    - cf-infra
- name: cfapi-ws
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-ws
  condition: cfapi-ws.enabled
  tags:
    - cf-infra
- name: cfapi-admin
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-admin
  condition: cfapi-admin.enabled
  tags:
    - cf-infra
- name: cfapi-endpoints
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-endpoints
  condition: cfapi-endpoints.enabled
  tags:
    - cf-infra
- name: cfapi-terminators
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-terminators
  condition: cfapi-terminators.enabled
  tags:
    - cf-infra
- name: cfapi-sso-group-synchronizer
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-sso-group-synchronizer
  condition: cfapi-sso-group-synchronizer.enabled
  tags:
    - cf-infra
- name: cfapi-buildmanager
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-buildmanager
  condition: cfapi-buildmanager.enabled
  tags:
    - cf-infra
- name: cfapi-cacheevictmanager
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-cacheevictmanager
  condition: cfapi-cacheevictmanager.enabled
  tags:
    - cf-infra
- name: cfapi-eventsmanagersubscriptions
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-eventsmanagersubscriptions
  condition: cfapi-eventsmanagersubscriptions.enabled
  tags:
    - cf-infra
- name: cfapi-kubernetesresourcemonitor
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-kubernetesresourcemonitor
  condition: cfapi-kubernetesresourcemonitor.enabled
  tags:
    - cf-infra
- name: cfapi-environments
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-environments
  condition: cfapi-environments.enabled
  tags:
    - cf-infra
- name: cfapi-gitops-resource-receiver
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-gitops-resource-receiver
  condition: cfapi-gitops-resource-receiver.enabled
  tags:
    - cf-infra
- name: cfapi-downloadlogmanager
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-downloadlogmanager
  condition: cfapi-downloadlogmanager.enabled
  tags:
    - cf-infra
- name: cfapi-teams
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-teams
  condition: cfapi-teams.enabled
  tags:
    - cf-infra
- name: cfapi-kubernetes-endpoints
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-kubernetes-endpoints
  condition: cfapi-kubernetes-endpoints.enabled
  tags:
    - cf-infra
- name: cfapi-test-reporting
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfapi-test-reporting
  condition: cfapi-test-reporting.enabled
  tags:
    - cf-infra
- name: cfui
  version: "*"
  repository: https://chartmuseum.codefresh.io/cfui
  condition: cfui.enabled
  tags:
  - cf-infra
- name: k8s-monitor
  version: "*"
  repository: https://chartmuseum.codefresh.io/k8s-monitor
  condition: k8s-monitor.enabled
  tags:
  - cf-infra
- name: runtime-environment-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/runtime-environment-manager
  condition: runtime-environment-manager.enabled
  tags:
  - cf-infra
- name: cf-broadcaster
  version: "*"
  repository: https://chartmuseum.codefresh.io/cf-broadcaster
  condition: cf-broadcaster.enabled
  tags:
  - cf-infra
- name: helm-repo-manager
  version: "*"
  repository: https://chartmuseum.codefresh.io/helm-repo-manager
  condition: helm-repo-manager.enabled
  tags:
  - cf-infra
- name: hermes
  version: "*"
  repository: https://chartmuseum.codefresh.io/hermes
  condition: hermes.enabled
  tags:
  - cf-infra
- name: nomios
  version: "*"
  repository: https://chartmuseum.codefresh.io/nomios
  condition: hermes.enabled
  tags:
  - cf-infra
- name: cronus
  version: "*"
  repository: https://chartmuseum.codefresh.io/cronus
  condition: hermes.enabled
  tags:
  - cf-infra
