apiVersion: v2
description: Codefresh CD pipeline management platform for Kubernetes
name: codefresh
version: 1.3.10
kubeVersion: '>=1.19.0-0'
keywords:
  - codefresh
  - kubernetes
  - pipeline
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
sources:
  - https://github.com/codefresh-io/cf-helm
maintainers:
  - name: Codefresh Authors
    email: dev@codefresh.io
appVersion: 1.3.0
dependencies:
  - name: consul
    version: 10.3.9
    repository: https://charts.bitnami.com/bitnami
    condition: consul.enabled
    tags:
      - cf-infra
  - name: mongodb
    version: 0.4.13
    repository: file://pv-charts/mongodb
    condition: mongo.enabled,global.mongoDeploy
    tags:
      - cf-infra
  - name: postgresql
    version: 0.7.2
    repository: file://pv-charts/postgresql
    condition: postgresql.enabled
    tags:
      - cf-infra
  - name: redis
    version: 16.13.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cf-infra
  - name: rabbitmq
    version: 10.1.8
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
    tags:
      - cf-infra
  - name: nats
    version: 7.4.8
    repository: https://charts.bitnami.com/bitnami
    condition: nats.enabled
    tags:
      - cf-infra
  - name: builder
    repository: https://chartmuseum.codefresh.io/builder
    condition: builder.enabled
    version: 1.0.2
    tags:
      - cf-infra
  - name: ingress-nginx
    version: 4.1.0
    repository: 'https://kubernetes.github.io/ingress-nginx'
    condition: ingress-nginx.enabled
    tags:
      - cf-infra
  - name: cluster-providers
    version: "~1.10.0"
    repository: https://chartmuseum.codefresh.io/cluster-providers
    tags:
      - cf-infra
  - name: kube-integration
    version: "~1.25.0"
    repository: https://chartmuseum.codefresh.io/kube-integration
    tags:
      - cf-infra
  - name: charts-manager
    version: "~1.9.0"
    repository: https://chartmuseum.codefresh.io/charts-manager
    tags:
      - cf-infra
  - name: cfsign
    version: "~1.4.0"
    repository: https://chartmuseum.codefresh.io/cfsign
    condition: cfsign.enabled
    tags:
      - cf-infra
  - name: tasker-kubernetes
    version: "~1.17.0"
    repository: https://chartmuseum.codefresh.io/tasker-kubernetes
    tags:
      - cf-infra
  - name: context-manager
    version: "~2.20.0"
    repository: https://chartmuseum.codefresh.io/context-manager
    tags:
      - cf-infra
      - argo-platform
  - name: pipeline-manager
    version: "~3.121.0"
    repository: https://chartmuseum.codefresh.io/pipeline-manager
    tags:
      - cf-infra
  - name: gitops-dashboard-manager
    version: "~1.8.0"
    repository: https://chartmuseum.codefresh.io/gitops-dashboard-manager
    tags:
      - cf-infra
  - name: cfapi
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi
    condition: cfapi.enabled
    tags:
      - cf-infra
  - name: cfapi-internal
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-internal
    condition: cfapi-internal.enabled
    tags:
      - cf-infra
  - name: cfapi-ws
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-ws
    condition: cfapi-ws.enabled
    tags:
      - cf-infra
  - name: cfapi-admin
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-admin
    condition: cfapi-admin.enabled
    tags:
      - cf-infra
  - name: cfapi-endpoints
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-endpoints
    condition: cfapi-endpoints.enabled
    tags:
      - cf-infra
  - name: cfapi-terminators
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-terminators
    condition: cfapi-terminators.enabled
    tags:
      - cf-infra
  - name: cfapi-sso-group-synchronizer
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-sso-group-synchronizer
    condition: cfapi-sso-group-synchronizer.enabled
    tags:
      - cf-infra
  - name: cfapi-buildmanager
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-buildmanager
    condition: cfapi-buildmanager.enabled
    tags:
      - cf-infra
  - name: cfapi-cacheevictmanager
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-cacheevictmanager
    condition: cfapi-cacheevictmanager.enabled
    tags:
      - cf-infra
  - name: cfapi-eventsmanagersubscriptions
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-eventsmanagersubscriptions
    condition: cfapi-eventsmanagersubscriptions.enabled
    tags:
      - cf-infra
  - name: cfapi-kubernetesresourcemonitor
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-kubernetesresourcemonitor
    condition: cfapi-kubernetesresourcemonitor.enabled
    tags:
      - cf-infra
  - name: cfapi-environments
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-environments
    condition: cfapi-environments.enabled
    tags:
      - cf-infra
  - name: cfapi-gitops-resource-receiver
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-gitops-resource-receiver
    condition: cfapi-gitops-resource-receiver.enabled
    tags:
      - cf-infra
  - name: cfapi-downloadlogmanager
    version: "~21.164.0"
    repository: https://chartmuseum.codefresh.io/cfapi-downloadlogmanager
    condition: cfapi-downloadlogmanager.enabled
    tags:
      - cf-infra
  - name: cfui
    version: "~14.71.0"
    repository: https://chartmuseum.codefresh.io/cfui
    condition: cfui.enabled
    tags:
      - cf-infra
  - name: k8s-monitor
    version: "~4.8.0"
    repository: https://chartmuseum.codefresh.io/k8s-monitor
    condition: k8s-monitor.enabled
    tags:
      - cf-infra
  - name: runtime-environment-manager
    version: "~3.22.0"
    repository: https://chartmuseum.codefresh.io/runtime-environment-manager
    condition: runtime-environment-manager.enabled
    tags:
      - cf-infra
  - name: cf-broadcaster
    version: "~1.10.0"
    repository: https://chartmuseum.codefresh.io/cf-broadcaster
    condition: cf-broadcaster.enabled
    tags:
      - cf-infra
  - name: helm-repo-manager
    version: "~0.9.0"
    repository: https://chartmuseum.codefresh.io/helm-repo-manager
    condition: helm-repo-manager.enabled
    tags:
      - cf-infra
  - name: hermes
    version: "~0.18.0"
    repository: https://chartmuseum.codefresh.io/hermes
    condition: hermes.enabled
    tags:
      - cf-infra
  - name: nomios
    version: "~0.9.0"
    repository: https://chartmuseum.codefresh.io/nomios
    condition: hermes.enabled
    tags:
      - cf-infra
  - name: cronus
    version: "~0.6.0"
    repository: https://chartmuseum.codefresh.io/cronus
    condition: hermes.enabled
    tags:
      - cf-infra
