dependencies:
- name: consul
  version: 1.1.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: consul.enabled
  tags:
  - infra
- name: mongodb
  version: 0.4.12
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mongo.enabled
  tags:
  - infra
- name: postgresql
  version: 0.7.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - infra
- name: redis
  version: 0.8.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - infra
- name: rabbitmq
  version: 0.6.15
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
  - infra
- name: nats
  version: 0.1.1
  repository: file://../nats
  condition: nats.enabled
  tags:
  - infra
  - saas
- name: builder
  repository: file://charts/builder
  condition: builder.enabled
  version: 0.1.2
  tags:
  - infra
- name: runner
  repository: file://charts/runner
  condition: runner.enabled
  version: 0.1.2
  tags:
  - infra
- name: registry
  version: 0.1.0
  repository: file://../registry
  condition: registry.enabled
  tags:
  - infra
- name: ingress
  version: 0.1.7
  repository: file://../ingress
  condition: ingress.enabled
- name: cluster-providers
  version: 0.0.2
  repository: file://charts/cluster-providers
- name: kube-integration
  version: 0.0.3
  repository: file://charts/kube-integration
- name: accounts-referrals
  version: 0.0.2
  repository: file://charts/accounts-referrals
  tags:
  - saas
- name: charts-manager
  version: 0.0.2
  repository: file://charts/charts-manager
  tags:
  - saas
- name: mailer
  version: 0.0.2
  repository: file://charts/mailer
  tags:
  - saas
- name: payments
  version: 0.1.6
  repository: file://charts/payments
  tags:
  - saas
- name: cfsign
  version: 0.3.1
  repository: file://charts/cfsign
  condition: cfsign.enabled
  tags:
  - saas
- name: internal-status-page
  version: 0.0.2
  repository: file://charts/internal-status-page
  condition: internal-status-page.enabled
  tags:
  - saas
- name: segment-reporter
  version: 0.0.3
  repository: file://charts/segment-reporter
  tags:
  - saas
- name: workflow-baseline-invoker
  version: 0.0.4
  repository: file://charts/workflow-baseline-invoker
  tags:
  - saas
- name: salesforce-reporter
  version: 0.1.2
  repository: file://charts/salesforce-reporter
  tags:
  - saas
- name: tasker-kubernetes
  version: 0.0.2
  repository: file://charts/tasker-kubernetes
  tags:
  - saas
- name: context-manager
  version: 0.0.1
  repository: file://charts/context-manager
  tags:
  - saas
- name: pipeline-manager
  version: 0.0.1
  repository: file://charts/pipeline-manager
  tags:
  - saas
- name: cfui
  version: 1.1.2
  repository: http://chartmuseum.codefresh.io
  condition: cfui.enabled
  tags:
  - saas
  - infra
