dependencies:
- name: consul
  version: 1.1.2
  repository: file://pv-charts/consul
  condition: consul.enabled
  tags:
  - infra
- name: mongodb
  version: 0.4.12
  repository: file://pv-charts/mongodb
  condition: mongo.enabled
  tags:
  - infra
- name: postgresql
  version: 0.7.1
  repository: file://pv-charts/postgresql
  tags:
  - infra
- name: redis
  version: 0.8.0
  repository: file://pv-charts/redis
  tags:
  - infra
- name: rabbitmq
  version: 0.6.15
  repository: file://pv-charts/rabbitmq
  tags:
  - infra
- name: nats
  version: 0.1.1
  repository: file://../nats
  condition: nats.enabled
  tags:
  - infra
  - saas
- name: builder
  repository: file://local-charts/builder
  condition: builder.enabled
  version: 0.1.3
  tags:
  - infra
- name: runner
  repository: file://local-charts/runner
  condition: runner.enabled
  version: 0.1.3
  tags:
  - infra
- name: registry
  version: 0.1.0
  repository: file://../registry
  condition: registry.enabled
  tags:
  - infra
- name: ingress
  version: 0.1.7
  repository: file://../ingress
  condition: ingress.enabled
- name: cluster-providers
  version: 0.0.2
  repository: file://local-charts/cluster-providers
- name: kube-integration
  version: 0.0.3
  repository: file://local-charts/kube-integration
- name: accounts-referrals
  version: 0.0.2
  repository: file://local-charts/accounts-referrals
  tags:
  - saas
- name: charts-manager
  version: 0.0.2
  repository: file://local-charts/charts-manager
  tags:
  - saas
  - infra
- name: mailer
  version: 0.0.2
  repository: file://local-charts/mailer
  tags:
  - saas
- name: payments
  version: 0.1.6
  repository: file://local-charts/payments
  tags:
  - saas
- name: cfsign
  version: 0.3.1
  repository: file://local-charts/cfsign
  condition: cfsign.enabled
  tags:
  - saas
- name: internal-status-page
  version: 0.0.2
  repository: file://local-charts/internal-status-page
  condition: internal-status-page.enabled
  tags:
  - saas
- name: segment-reporter
  version: 0.0.3
  repository: file://local-charts/segment-reporter
  tags:
  - saas
- name: workflow-baseline-invoker
  version: 0.0.4
  repository: file://local-charts/workflow-baseline-invoker
  tags:
  - saas
- name: salesforce-reporter
  version: 0.1.2
  repository: file://local-charts/salesforce-reporter
  tags:
  - saas
- name: tasker-kubernetes
  version: 0.0.2
  repository: file://local-charts/tasker-kubernetes
  tags:
  - saas
- name: context-manager
  version: 0.0.1
  repository: file://local-charts/context-manager
  tags:
  - saas
  - infra
- name: pipeline-manager
  version: 0.0.1
  repository: file://local-charts/pipeline-manager
  tags:
  - saas
  - infra
- name: cfapi
  version: ~0.2.1
  repository: file://local-charts/cfapi
  condition: cfapi.enabled
  tags:
  - saas
  - infra
- name: cfui
  version: 2.4.83
  repository: http://chartmuseum.codefresh.io
  condition: cfui.enabled
  tags:
  - saas
  - infra
- name: onboarding-status
  version: 1.0.53
  repository: http://chartmuseum.codefresh.io
  condition: onboarding-status.enabled
  tags:
  - saas
  - infra
- name: cfanalytic
  version: 1.0.37
  repository: http://chartmuseum.codefresh.io
  condition: cfanalytic.enabled
  tags:
  - saas
  - infra
- name: runtime-environment-manager
  version: 1.0.9
  repository: http://chartmuseum.codefresh.io
  condition: runtime-environment-manager.enabled
  tags:
  - saas
  - infra
- name: helm-repo-manager
  version: ~0.2.5-any
  repository: '@codefresh'
  condition: helm-repo-manager.enabled
  tags:
  - helm
  - chartmuseum
- name: hermes
  version: ~0.9.0-any
  repository: '@codefresh'
  condition: hermes.enabled
  tags:
  - trigger
  - trigger-manager
- name: nomios
  version: ~0.4.0-any
  repository: '@codefresh'
  condition: hermes.enabled
  tags:
  - trigger
  - event-provider
  - registry
  - dockerhub
- name: cronus
  version: ~0.2.0-any
  repository: '@codefresh'
  condition: hermes.enabled
  tags:
  - trigger
  - event-provider
  - cron
