dependencies:
- name: consul
  version: 0.3.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: mongodb
  version: 0.4.12
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: postgresql
  version: 0.7.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 0.8.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: rabbitmq
  version: 0.5.3
  repository: https://kubernetes-charts.storage.googleapis.com/
# Helm 2.5.1 should include fix that will allow mixin requirements.yaml and subcharts
- name: nats
  version: 0.1.0
  repository: file://../nats
- name: registry
  version: 0.1.0
  repository: file://../registry
- name: ingress
  version: 0.1.0
  repository: file://../ingress
  condition: ingress.enabled
- name: cluster-providers
  version: 0.0.1
  repository: file://charts/cluster-providers
  tags:
    - saas
- name: multiple-clusters
  version: 0.0.1
  repository: file://charts/multiple-clusters
  tags:
    - saas
- name: kube-integration
  version: 0.0.1
  repository: file://charts/kube-integration
  tags:
    - saas
- name: accounts-referrals
  version: 0.0.1
  repository: file://charts/accounts-referrals
  tags:
    - saas
- name: mailer
  version: 0.0.1
  repository: file://charts/mailer
  tags:
    - saas
- name: payments
  version: 0.1.2
  repository: file://charts/payments
  tags:
    - saas
- name: cfsign
  version: 0.1.0
  repository: file://charts/cfsign
  tags:
    - saas
- name: internal-status-page
  version: 0.0.1
  repository: file://charts/internal-status-page
  tags:
    - saas
- name: segment-reporter
  version: 0.0.1
  repository: file://charts/segment-reporter
  tags:
    - saas
- name: workflow-baseline-invoker
  version: 0.0.1
  repository: file://charts/workflow-baseline-invoker
  tags:
    - saas

