global:
    mongodbPassword: ENC[AES256_GCM,data:o84otffg4Nu0b78C,iv:Ar0k9mYsOUKVm6e4iY2TLGLp+aztxJp91mg+w021rPE=,tag:ziy/mf4Ecgocbse9z9X8fg==,type:str]
    mongodbUsername: ENC[AES256_GCM,data:uyrv0yAI,iv:FZBp1KZTC3/P24tYn3R+J90QKSnO1JXtf/+QZjQv9uw=,tag:cmoWYhuWiuxWeTRQlSM6QA==,type:str]
    # github internal token
    githubInternalToken: ENC[AES256_GCM,data:6jLebj3WwAEIjuwiCa1KTJe063+sF7bDQAtREpHAFCfi6cgj8asgXA==,iv:NvmhDwQclQrpBXnB0vqNhxb7SkA/+qMNUbBl8la88HQ=,tag:V47YPf95+/IcPRjnpYh/EQ==,type:str]
    # override mongodb root password
mongodb:
    mongodbRootPassword: ENC[AES256_GCM,data:UZcdCZAkKSUBFw==,iv:DUnWOyoqqLFO1lrHh4Hom9nOrCSUAhqoBpLPAd1ials=,tag:2bD0CS81A0RYgbxqSC6/lw==,type:str]
    # rabbitmq credentials
rabbitmq:
    rabbitmqUsername: ENC[AES256_GCM,data:fdTXlg==,iv:qOE1V1c2BVYxnqIir6cb/m/ZL2u8uhV44+y5lUhCCJw=,tag:ubpQuT3n6DQTyvWVoxNikw==,type:str]
    rabbitmqPassword: ENC[AES256_GCM,data:KCar6qZu92lG9urO,iv:JFizkljZU0Ba8Gf5krorkEanjVFk/DZI/PLjHMW6TYk=,tag:2yhXn+glM5uKg7iguifWLg==,type:str]
    # postgres credentials
postgresql:
    postgresUser: ENC[AES256_GCM,data:91klCFgi/DQ=,iv:AOqeWvZcW4uITu/B+DQ6HiltTfrz7wYZ3Rf1VuI/4nM=,tag:6Tq9zYs2gUcJPtLaw8D+Ng==,type:str]
    postgresPassword: ENC[AES256_GCM,data:N8bo63t7XyOmq2ji,iv:9xSMsRJnyDRV+uSw5qLi3VzFgzFZLknNGejfTRS0yqk=,tag:NXSjXiT6E6iCplafCh4ZBQ==,type:str]
    # redis credentials
redis:
    redisPassword: ENC[AES256_GCM,data:aR4lure1GehRS5Py,iv:0ixJOfk/HhauppX2D/lyNLBG8bqc+GBASmT8jzpZJ70=,tag:0lrdheehULJBhBU6rZFYEg==,type:str]
    # misc
slackAppID: ENC[AES256_GCM,data:mtuar3b9r9KQzLKF8y9imwWJviF8rg==,iv:W4nYxEpUHN4dyU4At7FogdCzC7Vm1avtg3pirGWW17Q=,tag:724wf73DiPH6hNV4FOjdRg==,type:str]
slackAppSecret: ENC[AES256_GCM,data:nPTc5vISGnSrSaWQS42IlPO9lmerKGYVI2mHfM9L+HQ=,iv:fitUxpU8hht9ykYFM2s+cVwEcEHjtzQkNUbFNIAZB6s=,tag:Vioii5eH1pK4+sdkLuIXsw==,type:str]
# stripe keys
stripeSecretKey: ENC[AES256_GCM,data:+KN+800xqvxS8u80cDdBAAMM9r1Fq0AHW4cJqS1VuFo=,iv:b4ODgF6SP3LHkORU0kTINw7iT5duLejWy5/NnO9WuAU=,tag:5xO79Z3LQSFfPv0o/T7tgg==,type:str]
stripePublicKey: ENC[AES256_GCM,data:WzG0y7AbZYY8fYSn0taecMhUkmEiThJ+AxwfVdsq1GU=,iv:qmlRKYiuIZbtL4e5TUIhYSroP9pfNvPAw5uIHMUK7Tk=,tag:smvSg74K1jnVwz00umV9IA==,type:str]
stripeWebhookSecret: ENC[AES256_GCM,data:eQxC/Cy1SP6u6vdPMJDs2DRc0Ae/zVhxwUE62YQbLjrRV5jhr5k=,iv:7++33RG70aYvwidOV8cD2QM7gTCcEnGhl8Q3jsWFkkI=,tag:a4gneeTiA1I6uk1lEx95zw==,type:str]
# rollbar access token
rollbarAccessToken: ENC[AES256_GCM,data:sF6TiCRySmqyitR32D9qaLj8Q8YjP6pl/PLdltyI3t4=,iv:/JJdykZ6golOJ+EMtM3+Xgwu70zBy/pclxNlIPPjRRM=,tag:sneyzf1s4pqAuy63WKHzKQ==,type:str]
# all these invalid secrets are here because of cfapi bugs!
logglyToken: ENC[AES256_GCM,data:wCGSLxbRNRwF95F6ZA==,iv:L7UJ6WeVPMZdZkH3uka1SIyWV+wmgqZqcCM1u0TrYx8=,tag:bqHXeEzDJyBaGEFS8T393g==,type:str]
bitbucketClientID: ENC[AES256_GCM,data:i2nIfRPYFrBlFQ==,iv:bHwE3e1VodbDzJcdJ97G8a7zUIn4HL2A4C9rsBochYw=,tag:GP1mcyJgHx15e4qnTS4LoQ==,type:str]
bitbucketClientSecret: ENC[AES256_GCM,data:jHqPMhlFisCNH8m3RLE=,iv:MNK53wUHGUV95Y5rxvKdE7QzX2es65EmOWX9+zoys6w=,tag:u3yjPl3xvkHGd+fx75LK7A==,type:str]
# CFCR registry auth API key
registryAuthKey: ENC[AES256_GCM,data:FGKgmCqkROSPDEijjRCYdlZgV3o/+ZzNSUfJo/gM8U28OUP+,iv:tYwd00/JSjGfrjQqFuYpcb73KUumpoQLIiXYtAkgMy8=,tag:WbYbts0dy0MAwIxKJ2Fzgg==,type:str]
# Internal Registry admin token
registryAdminToken: ENC[AES256_GCM,data:uDw+f9Y2Os8sLzX0VKKk4zrKZiAMd9SyB7BNWDP9yVE=,iv:3JRa4eu6KPRSMvFnQ5ItfM6WkSe6Gm3JKnxRaNk1ZrU=,tag:E4zmUizXPFYWhaBDvroTCw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:839151377425:key/8f4d2cf9-30fb-4f16-a9a8-6cfb6815626e
        created_at: '2017-10-14T02:51:16Z'
        enc: AQICAHh7tK2dh55HkjrL+q3qHw1Fs/LKV7qodM1JtjJ3RA8cDwGjeiW49RpD5IGdfum5AtRnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpvM7Vcl6IMVGGNBeAgEQgDta0tJP879+IP+lrU+LVOjlRfAJa6K0nmhUcBUm2z9u2hfDIpXy2iiV7Gc4F0YPWh2CAVfx+MB/EP1ZAQ==
    lastmodified: '2017-10-14T02:51:22Z'
    mac: ENC[AES256_GCM,data:OgyhDnTPKTH43tjSzt9eIvctGYdK1fk/pcGz+ntKyKg+myX2hVIKK4lNvS8WgTlZKHXoa4UTb2jvDyzew+cJRgzvG7ER9ufvnc4IFaPXFNZMwunlfCEQ2ujthyt/dMNcLsI/gjW7ZaZsWOBTLY52BI0MQxhoS+gmXSFMFFYwv8E=,iv:dF6Tr7DE7aFqYuyVR5nS+MdjSoCMVXRnzlerEj3r86E=,tag:DZwZad4gWytxi5qtrqRLpg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 2.0.9
