global:
    mongodbPassword: ENC[AES256_GCM,data:76E7+LOEltPF3D00,iv:brKAs7fiBR/Jzs4sAJ3nOsHcCKjQV6Y1DwZzUTy1Sas=,tag:BLmqZpMq+GkginfpULzQEg==,type:str]
    mongodbUsername: ENC[AES256_GCM,data:88fEFFDm,iv:0XZvWYXSCdYZOzUJBqJXGIABETsC6KiTB/n+zClZuyw=,tag:pZIS0I/8HiF3UG32ujNz7Q==,type:str]
mongodb:
    mongodbRootPassword: ENC[AES256_GCM,data:pbxRTpc7AOpGGw==,iv:ORMTj8bAUbbOmO2D0H+PinHloDdHCc6HTwbDg6yZ07U=,tag:6FOUsSCrSrBoz5MP58mLCA==,type:str]
    # rabbitmq credentials
rabbitmq:
    rabbitmqUsername: ENC[AES256_GCM,data:XEhXhQ==,iv:tWu3Y6R0Y9kwkEHzTYDR8RaGs0eZu52EYurCFd6HcPI=,tag:XbDmuy7wOhLTiacHrSGsUw==,type:str]
    rabbitmqPassword: ENC[AES256_GCM,data:jpMCE0RiRI6H/kex,iv:JUf8KYQvzSFmw4Q2+xlnF/TOjjIXpbGcAA1vZ1fHOWw=,tag:HeThFnb00QMrNHEa6qWtZA==,type:str]
    # postgres credentials
postgresql:
    postgresUser: ENC[AES256_GCM,data:uxilRR7cISo=,iv:7LgKba+umEysGfO2Lzmu9knCkwfK4X2bXz8yp26Ky5E=,tag:20WUii/a8ul9QQMkMGhUag==,type:str]
    postgresPassword: ENC[AES256_GCM,data:xh1I33H3zWkMAXkv,iv:m3opMeFURdAO+YTvyYD4mkAXb6CLmpDUPL+fg1ER6u4=,tag:E/eE7YnYrgzgNuEgLoeDlA==,type:str]
    # redis credentials
redis:
    redisPassword: ENC[AES256_GCM,data:qm9N+k1MALb7kOvS,iv:GeGkV/A3b7U4+40bi8Ljh9W7xXL3rQN5s1h7rBQVevc=,tag:qaB8Usn2Rg6TFrXBU2mnlQ==,type:str]
    # misc
apiSafeSecret: ENC[AES256_GCM,data:QbyVHjNaV0uKAeU8/NOyMXHn2URWz4Nwyw==,iv:kqwUaU95366IQ4mZpdYTXVewJe6Cz8wrvwxkvnSF2FE=,tag:mY9DKcPDPvSzJJbHCqxiYA==,type:str]
firebaseSecret: ENC[AES256_GCM,data:1Fp4OSTB7EGYpMNTFDUMvMPp9Nperv+27FEZYnQ1AJQ6WSTNy2X0Eg==,iv:4KgeLp66zE09is68rI9k5URGp9reBoLi1msSZ1q5wh8=,tag:SqfDjmNGGz2BzGQgqyd4Nw==,type:str]
slackAppID: ENC[AES256_GCM,data:wz5z5afK+yUwXgDw/jhCEap6UTP1rw==,iv:g4WJTstd2LUg2IWIfcXOE0NleMRFZrs9iRQyhdeUUUo=,tag:ZSYyTBZHjgo5m1DTLNhUJQ==,type:str]
slackAppSecret: ENC[AES256_GCM,data:MOFDMt50fyef9nBPbl28SeVQvCwst8iggf4/rPTifKc=,iv:+kbGc/7KXZ7Th3iFNIH9OSbJXR/Mc6FsirJKhxi1eZs=,tag:iqBCaaBMlp1SbqjbutTGXA==,type:str]
# stripe keys
stripeSecretKey: ENC[AES256_GCM,data:QF5pCNg/6pavIxyTyn+7A67UR5w7DfH69enFYybI7Wk=,iv:XoiQfRvXVBNi8EdQuZYXt2rV5gd9Q0paneLQ06x8paQ=,tag:TDSk1nxTsoldZhG8yKHCEg==,type:str]
stripePublicKey: ENC[AES256_GCM,data:pl07aPZTby+i7Cn+TVBlASOWJykZZ/MQEruMY7bZn80=,iv:KrOtUdZtnHmAjJb1OxWMerVRbGdBTz4uqYMYTlK14Dc=,tag:Cdg1zfrldzd4lVC/p/I76Q==,type:str]
stripeWebhookSecret: ENC[AES256_GCM,data:vY1C7Ywa039bEYojgSVicx/VD2ithk1pIrOZogGXZ27xiXY0+tU=,iv:bbMvjeSComyDAOzJx8y52qmLxKSEJGRadrHtFd+eLgU=,tag:tjve57BvY9rHQLCAuiAuvg==,type:str]
# github dev secrets
githubClientID: ENC[AES256_GCM,data:CP3RiP7SEqsjRRN4jwBjWR5vHks=,iv:7+y2SHKUKqHt143jZj1dpOS4XwyTu9mFGHVnToh3lfw=,tag:5JNvIRD+9Xs5omSuplJ0nA==,type:str]
githubClientSecret: ENC[AES256_GCM,data:OCaKq51zDU7YlYsMtoqiNl5LTtlLbW+tgBOwBdqSs2UY4beMdLKKIw==,iv:mCnQaRpYQE4F8KrVUu+lYx73ixMtF1eozrbV1DUvuMo=,tag:Z62gBOOLbzPndkjAGe+JbA==,type:str]
githubInternalToken: ENC[AES256_GCM,data:XopDOV/k4JTVUObeEBNTy8FK8ScrsR/AA6oxnkTxTCdrnoInLLtzKQ==,iv:mqE8gMyf81uIxFyLHFZUUkvSpSTk4t+drJE2s8QHulw=,tag:ryy0fyzab0Ix6KOzGkZrHQ==,type:str]
# bitbucket secrets
bitbucketClientID: ENC[AES256_GCM,data:bP+mHghUr9DKbCFgpQ+XyHa5,iv:vQs6B8rXcVXETf9Ez46AmWzeAcQUTvwW/w0bH7YZnSA=,tag:QK5c3hfsqjWAa30dcGLKeg==,type:str]
bitbucketClientSecret: ENC[AES256_GCM,data:NqCtolLPc2GEaTduDpgH7wT8nT8vWUWNu1hARXQBcP8=,iv:5KqJTDwAbGrwlWTwJ1TnAxruRMuS2zjxLpDhqcm6LpA=,tag:WI2qs7D7n89PEO3PfZaIBQ==,type:str]
# gitlab dev secrets
gitlabClientID: ENC[AES256_GCM,data:z4w+7vdP5AWJ1FMCSEbbiRFcYaQ6KGMUUugPfb+ci0kSFRMWVeSKCG2kg09ueyISkBF7YVDP+kPh4r+H+O3Jaw==,iv:Y977VbEewnWSMW5yNmvM46flWSUOnF8gqMMyBEkrpcQ=,tag:uj1Ny8XXpl3PmvNTYNHGrw==,type:str]
gitlabClientSecret: ENC[AES256_GCM,data:vLPQ5hkI9M+2gxd+ESqDwVe6exKVGUMIjIE55jSDRBsTu3ZcU+0Q4DH0bpRrgqGpdjwb/PFH4V0O1l69FjSw3Q==,iv:+SE8x6qJzkidLVC8v6KMzM98M3uGDbZrCglT7TCbcu4=,tag:c+bzI0pyEeO0PJxJ3x3/Dw==,type:str]
# new relic license
newrelicLicenseKey: ENC[AES256_GCM,data:E9p8P/uae5WV6UXw0EF3ryyWAIcGOdTcvskYza6XOIY1bXqFK4lqFA==,iv:p15GCIjAtf9bAsgPYGWsiy4lDpGTrHvSxxJy5UPVr6o=,tag:aUEzK9EhFmYYfOYagtgK3A==,type:str]
# rollbar access token
rollbarAccessToken: ENC[AES256_GCM,data:FMXGAbaAcVd/UBoQQxXyr3yagYA0O+xZ4I20kM+9Cuo=,iv:HRssZaStypn7TQQHcnNopHL3dfhKKP/BeeWtPBb0UV8=,tag:WqEZ4ZNzwk++ZnUxx3jttw==,type:str]
# all these invalid secrets are here because of cfapi bugs!
logglyToken: ENC[AES256_GCM,data:4YoxrBNziCljMye0Rg==,iv:LF1/fchq1YVbzgHSKaQP6sum8Rc8gg+mdKq9PS0d4y4=,tag:2MrKMxuEX/TSMyrEpqdJ5w==,type:str]
bitbucketClientID: ENC[AES256_GCM,data:s3KXmdBIgexnCw==,iv:0s3P8d6PnJkw7sSIOYcnwB8f+GYokMU+A1VvFBgBViw=,tag:tym6oqiBEYETwVAqZG7z1A==,type:str]
bitbucketClientSecret: ENC[AES256_GCM,data:IeHnA3Xstg1MWo6K5SQ=,iv:Yh0XIcPQZOazYnzhL3rwVAMKIeH//27FhNDCLQ7iOtc=,tag:NntcqOxkNp6jwYSRM+9UQg==,type:str]
# CFCR registry auth API key
registryAuthKey: ENC[AES256_GCM,data:ze+bFpOluhiF6w5wIPPqs9CfrVLRoRJTczECOaCIEguXznM7,iv:82KKZ03BPLebmfDOtYxSplJfkAfhIyzEoEX4tbpu4g4=,tag:ZYPMYylyFgRg3B1dc5k5lg==,type:str]
# Internal Registry admin token
registryAdminToken: ENC[AES256_GCM,data:AaeLcpjfTUxUk6/tYswtpPlcVp06F2FGoYriu1pB8aM=,iv:hgUfqkJaPu48QjIF4lpopYzsoM9Q4GX04EB9vCAHGfc=,tag:iiaAXDEY6ZfnsDCFYKU2Uw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:839151377425:key/8f4d2cf9-30fb-4f16-a9a8-6cfb6815626e
        created_at: '2017-07-17T12:55:06Z'
        enc: AQICAHh7tK2dh55HkjrL+q3qHw1Fs/LKV7qodM1JtjJ3RA8cDwHflIV/TiCcSyhovTm9oSquAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTEHDhpeDH5vJM281AgEQgDu/Haf/VjUi2V1BZdcxDdMvMspl+cajhZn2uxvbJN1kUVdCdJPTvcv+zpsAqiRFAlgk2/H7zg9U09gHbw==
    lastmodified: '2017-07-17T12:55:07Z'
    mac: ENC[AES256_GCM,data:3aZnM/D94nkk0mezoXDQ01pNj6AE9/17MSkDLBEJ9HCGwOtiFVX/eoQ2mQ+yOkzZoIKhLaa6B+yrj96rLnqBWk/ZQ9G+Xc+tP7Rrh6JKjcaZ04x8Y+VsoPC4TbGBeL8/TN6jx0YLbTkI+6ia9xQyHSOZQuVL3JU1hg49ZkjItVw=,iv:RnzPjqiZZS6JaN13Xpxw9r04xAtOA9nn7TWxaoManbo=,tag:ZJTzpE5grVCNorNyb0WVkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 2.0.9
