mongodb:
    mongodbUsername: ENC[AES256_GCM,data:pgxeRfYX,iv:exz23nZo/Ifs79rfacKxW/3RkLDw5SU7kRoiEoMpMuc=,tag:IBDuYudWY5qZB+vpg6dISw==,type:str]
    mongodbPassword: ENC[AES256_GCM,data:OcUjW+hgHC/efJ3Q,iv:Qok92AY3Bs42CMFCNaO7zEzEO7Ct8n3o8NFyW3FkcEk=,tag:WJYkeoESnw+XbZpNU0u2lw==,type:str]
    # rabbitmq credentials
rabbitmq:
    rabbitmqUsername: ENC[AES256_GCM,data:F3HQQw==,iv:YUFb0KELXjHgeaVDouom8Jo/BhtgsSyaiTk6FVi4Hmg=,tag:vSYvHJ/+Ju85oRQjup3JYQ==,type:str]
    rabbitmqPassword: ENC[AES256_GCM,data:WmEvAiacogL9S8Hr,iv:BK1AyD5kLE4duBI3d+Ud8NdLdoNuT9ZgmJ5MC4g5U9Y=,tag:KO4wlU33CCt6wmK/pcGDng==,type:str]
    # postgres credentials
postgresql:
    postgresUser: ENC[AES256_GCM,data:iOAnu7G47ok=,iv:uMo5BZfICkvMef4GGx2CnaEyFTuzEuGDMy64FUPTMKQ=,tag:0TIftyG3Ti3j6gX2N2i3pg==,type:str]
    postgresPassword: ENC[AES256_GCM,data:DHPpEPsn/iGU8oEe,iv:E4h3tyoLgFAeXElVBTPVK20XrMQTjibyyEf4/46ZjYE=,tag:6jjKvvSmpuP1/vMpZMJlaQ==,type:str]
    postgresDatabase: ENC[AES256_GCM,data:BfnzOoduohuj,iv:GaR+Z72lOEb+ZqB1tG442cz+K4BhZkkdMEQSbQizzFQ=,tag:TZQvZo17YmgnEMxgsgZJsA==,type:str]
    # redis credentials
redis:
    redisPassword: ENC[AES256_GCM,data:2l4UjtPlcZ8/WHuy,iv:gGihOL9uFIEjWXrLjv5xwt5zYuJRle//fWgfjeK9YSA=,tag:ydFadZ2xUM76T7VmJ4ABYg==,type:str]
    # misc
apiSafeSecret: ENC[AES256_GCM,data:RE/JaV7WvMOJgTIMECsJ8X5SC88LxgFsfQ==,iv:AiIG89ogE2l5UQuVP3xHOUmRVIvO4LDGTcVrqlv3XCE=,tag:uk3qpUH87k0u0PZWOugHqw==,type:str]
firebaseSecret: ENC[AES256_GCM,data:jzLH663HRJFJajHtG92dkQKnmx+1GmzVsFIzgpRuSekwWjbmkEp2Iw==,iv:FnBBRIpIiNc5UMYkKUJJv80PxrhNmicU5AA6CuxfTGw=,tag:sTUdfakpovcMqhqFwFnryQ==,type:str]
slackAppID: ENC[AES256_GCM,data:QGxv+olNrpYmMo67ZkAPpPy807GaAg==,iv:8uEYYfltEOKPZd33dA2ca9Lf84R5Z9w1tk+bio0EfAw=,tag:6et/nWC1sGMoy/4U+c+q6A==,type:str]
# stripe keys
stripeSecretKey: ENC[AES256_GCM,data:08b8+PbndzSlUb1OOVf0Fn5Tgn7fVU19cfsVAOFwBGU=,iv:nZ8a/4rsEcqwrwr47F6IdfRxjgi7r5DUAhnIQRsBeoc=,tag:fH513E2xcppqEUK3VJEN5g==,type:str]
stripePublicKey: ENC[AES256_GCM,data:iMBVl9CbMhZGTRTgw1nXJE1QWisLOKANWrz3p4k9Qkg=,iv:4XDw/VTtrVekLb/EA1Fb1Hdu9/aR17usOTfm7ehiX0M=,tag:4Rs3uemKnlG+I8JdQmfH7A==,type:str]
stripeWebhookSecret: ENC[AES256_GCM,data:yM1UmCvMCiEw9JTiElQ2eu7AqnYI/gsY33DAU2RwYtnqvWMUkEQ=,iv:SnbK7VzBL/Cd8cgRGJXZX8GEIAvEQ7FDjYrIe3YRBvk=,tag:fRuLNEYKIT8/bJnrwd+6SA==,type:str]
# github dev secrets
githubClientID: ENC[AES256_GCM,data:fIO4XvXXjvlhNMqsZG39EHnys/s=,iv:ay4Q+AD4Xi0HuK4+NNCT1QOzyZmgMU2NfWjcwxzrQe8=,tag:3jNNP3GTdWrt36M837vp/w==,type:str]
githubClientSecret: ENC[AES256_GCM,data:7d7sGsHHQ7YTgWSInZEAep1n6VXXdYCtfv4HsllHY8J9beFzS3qOxw==,iv:seeze0HFcvSiZDn3bxPcNH3iwv1q46V5BNg8kN6ewmQ=,tag:YnLFgsQANa76+FG7CB0kBg==,type:str]
githubInternalToken: ENC[AES256_GCM,data:ivZE/6C1EQw7zL3EBTZ07DtGLV9mNeG7hpZcEgzATkj8WfFHuUjidw==,iv:sX7NheQ6eB4gxyhqce3wffo5ydj9+wgVXeKqwJstHow=,tag:Y7HNVIR1Oe6oBSdYkO25gg==,type:str]
# gitlab dev secrets
gitlabClientID: ENC[AES256_GCM,data:UNAhnAAbEI7E7KU6HUCFtQGLe9EFQMKn2J7KZQeeP/a/RVSI8VXtBzxn5XapmV22mQkRsDMMb+YZxqdQl5RTFQ==,iv:qUQxbXlqPHu9ln0sw5YdSG90KtBecIqaxysW401dGpY=,tag:ncdlZVZ+KeqYda/oRjrIaw==,type:str]
gitlabClientSecret: ENC[AES256_GCM,data:eD413vIx7u8vx/3OOVByj7w2L12do91Y1qEiIJDMCaGApP06yKd4wl4Jy466HytLr9GUeAHVvMbbhWuxQ8Em0g==,iv:hnbbaZYP2pj/j9BXP+/gTgbvuScPbMQllWL8Z+a+zeA=,tag:uXj4Dz9jnXrdy77az2DA1Q==,type:str]
# new relic license
newrelicLicenseKey: ENC[AES256_GCM,data:VKdIS8xpvtjXYnR9X88iJpnehGVCknhYCZPnEThh/oO225xtLUbUKw==,iv:p4PMwNV6gp99+23LuoWQn2dn6V8ly4CZ7Tp+wwHlyBA=,tag:TFLrrrmpsp+UfAn+pmiRng==,type:str]
# rollbar access token
rollbarAccessToken: ENC[AES256_GCM,data:DYMXlqg7dWuOw9UG5IC8dps2Ws3Grb+cpt3fpaDQ84I=,iv:NjGXn8yudROLl2xvcIyoAnxMiWpiKN4q8i+wbctF4LQ=,tag:AQy2WRLncVlRIPFtwH0oDw==,type:str]
# all these invalid secrets are here because of cfapi bugs!
logglyToken: ENC[AES256_GCM,data:HxBpHBxGjBXw8zXoOw==,iv:tl1lNF7Scd6+jqY8ICOpqzFaCNI/P/LmFqlKeKZBf9c=,tag:6sV1OKLTi384nWft1RDtzg==,type:str]
bitbucketClientID: ENC[AES256_GCM,data:G4QJkn0Ea56iHw==,iv:wttDrR2nI7aMTnnTiveQTsk62LX7Et5Nv3B48CO43fU=,tag:0yuTcea4YxSzM/0XnNG+HA==,type:str]
bitbucketClientSecret: ENC[AES256_GCM,data:K9VADYRdNoQOxNXjiKA=,iv:4qnvraVDsGLEuytgbGjM2WFiZGvn4Ry3eSRRDT3QPL0=,tag:JN+7beXePcvPSS3NkVW3TQ==,type:str]
# CFCR registry auth API key
registryAuthKey: ENC[AES256_GCM,data:J7KLVWmDRBK3jKA78IOfTTGoFVyaZBcDMAIBJJ3sgMJ8CnDL,iv:eIaFtHou/FXFq7HMbdnIE11SWZH4ykRPznHhD/pED9A=,tag:9CnmjAKDNNwM5yYHUcunVQ==,type:str]
# Internal Registry admin token
registryAdminToken: ENC[AES256_GCM,data:5A4p5LXy9dVPbkfjsRs9n3yoFQu9QVvk6yWZ9Didu2g=,iv:29iGSy97vHY1rc/5Ug7nDRy23IJzenYVNNZaHueSn8Q=,tag:wdJcy5wDFLuWKkGJTN3b6Q==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:839151377425:key/8f4d2cf9-30fb-4f16-a9a8-6cfb6815626e
        created_at: '2017-07-12T13:50:55Z'
        enc: AQICAHh7tK2dh55HkjrL+q3qHw1Fs/LKV7qodM1JtjJ3RA8cDwEhPjn2c02Wpp20KwlNRfpmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAD8os8MT3XUIIU7AAgEQgDsQB+rOqzUjGrUvYu4BGetWwjPZ8qgfE7mAvP03Tqf1kAxL5dqU0wU19A1UKfH0qRV6KgW7ShKl4wYNJg==
    lastmodified: '2017-07-12T13:50:56Z'
    mac: ENC[AES256_GCM,data:dN8L6O8+V7Ph3XjuvPKVReedmkuETGe++3ZxWA7RvH9cO4aWgMLXRivZuONIY9pPM6Fm/2RaZ+Rcx9e8zypAphfkE05SUE7+jiCsiTja7fqsDODx33/nNeIuL/CXwwdVgZAJNnWBUIRHOEu09V6qYxJ1U2xGEPV/ZeXRs5JRUT8=,iv:YNOuuMr0uWDrp5nnKyXt1iPAmbNBsKQ+8W/0DcoZWKM=,tag:DCmwMXpDDzm/6AHNZd6aYg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 2.0.9
