mongodb:
    mongodbUsername: ENC[AES256_GCM,data:PEd1Mtvc,iv:J+m4L7srD7EfbtmvAwgaIi2bQ9rhU2z71N9LY97Qle4=,tag:4bnxgBgzFUpYsjyF/o87lQ==,type:str]
    mongodbPassword: ENC[AES256_GCM,data:yFOmEYZlngumDnf/,iv:i1pJnoBpXMZDS3oxnoKG484k/e+4WvtSbz1zhUj+gQY=,tag:dxViiWd1BNmj9ZeHl6NKJQ==,type:str]
    mongodbDatabase: ENC[AES256_GCM,data:TeXn5zRHVYv2,iv:6JhmY2LbV6KuxcuL+9+GHHSIXPlf7FHG9Ah7CtbGaqo=,tag:5e0vqqpIieMBPyTvOZ0DTA==,type:str]
    # rabbitmq credentials
rabbitmq:
    rabbitmqUsername: ENC[AES256_GCM,data:WCSp6w==,iv:vf3lVgjZMKIPtxtZ6jCM06975SCXYfkTU8wH9j3clV0=,tag:TqXaGUm3555DA8/FzAcrFA==,type:str]
    rabbitmqPassword: ENC[AES256_GCM,data:Zjh80pf/mxLLSIao,iv:SekQm5DoTrVLvpLRRPDeKp6+sJVDvv1oeLYwvvvuLzU=,tag:qY/MBPW7hOfMqicq4JdUKg==,type:str]
    # postgres credentials
postgresql:
    postgresUser: ENC[AES256_GCM,data:VlOoeTfImHE=,iv:23M90Ma2jxjYHoy+CBiAXaq/roefoI2Gf8hqcFEohK4=,tag:kyJblUQXOWBlQkMThLgvfQ==,type:str]
    postgresPassword: ENC[AES256_GCM,data:F9PnNCFqggsD/Ees,iv:zshV5KlOvGLJzkd05kk+Rv27Rg4fNMIMh9NwO3Y46l8=,tag:981UvI6oOwFrF+8MkMQ6Sw==,type:str]
    postgresDatabase: ENC[AES256_GCM,data:xLdQLAgXqX1X,iv:cE0ZuH2rDk0+r6GDbzO9HmgrOT2/v5CGHrBeZHON2zM=,tag:vEa6X14hxaW0IZ4tYSKJbQ==,type:str]
    # redis credentials
redis:
    redisPassword: ENC[AES256_GCM,data:NCjmDJV3OZbc5aB6,iv:aTnR9sZf0FGePhkMWNElsF/oRriH59qz38x+XpW0ZEs=,tag:4zVm3/suUgJQvuYftnC3yA==,type:str]
    # misc
apiSafeSecret: ENC[AES256_GCM,data:Wj67B3sPO+w/EEmNqFyzUbtjL5ib9cVoYg==,iv:qiMSsQUdm27n2oPncNMCPOLfLTXnPhi09Pfp5eg1VAA=,tag:yyZq0FpitoPqT65q/hIcsA==,type:str]
firebaseSecret: ENC[AES256_GCM,data:eERJMOnleMuYTfqJfIv5OqeCrXun8PvKY3OnlpxHCeeYbEYTGsJOzQ==,iv:H6jnpHJqd9+2Cit65diK3KJ6QxsGWSha9MVkfKzMp3A=,tag:mikMOzApnZjTN0vOZ4ZLiQ==,type:str]
slackAppID: ENC[AES256_GCM,data:gt/G+xPipUvmOn2Su/QPy+zhfmHoAA==,iv:ldIUblHgvOdf6P2mVUBFMlKZEplE3YrCjNephtkZinw=,tag:CI6MwHfh2131yf339BV9zg==,type:str]
# stripe keys
stripeSecretKey: ENC[AES256_GCM,data:dAKCo6MsgU0jX4BB6yYZBFEsBHCO1gmaKlAxYxc1YvE=,iv:LswtQTZ/UsPD+Ppqwm0X5hy/ckYpAOQm4BGx5yUyz0o=,tag:dtYHqE0S5zAj6f7K8Sg8dA==,type:str]
stripePublicKey: ENC[AES256_GCM,data:TJmcxSdSJLRAWMfVGg5K/KobdOfDB5Q/CCfS/P9vyIY=,iv:W/0NcOWKnHIuKdvMLZDnZm+n9PLh56KJWAwZTfBIxto=,tag:DaFwanISCoVJTK5bQcM8Vg==,type:str]
stripeWebhookSecret: ENC[AES256_GCM,data:OGI1SBTEtJAn7pdNK/d60EC+L7N/fpcUidWg2jpRLBAWV83xkqI=,iv:R1VUrTY5q/5j9q8lVAJaLHXkRz5tlE3CCmlSa872ntM=,tag:G6Yf2Hag4nNzq41TR7kdhw==,type:str]
# github dev secrets
githubClientID: ENC[AES256_GCM,data:tyAZrX9Ie91++duhm52s++cTgH8=,iv:wub3z4fjc6CnJQD/94rXjmmRcqO3h1zvA07j7vAQxV0=,tag:w0vTxs1a4IXSOW9EdjJ2hw==,type:str]
githubClientSecret: ENC[AES256_GCM,data:fzumRVYFveyaC8Mn2s8Q40dhts4ctSGYukJ/9heQua2oZBnZvdlDeQ==,iv:V0bIfuIM8nsN2DCpe56FsxSv2eb7ETFaWQRIXqYVzW4=,tag:sDum5YXq+cOjMFMiq9JKOw==,type:str]
githubInternalToken: ENC[AES256_GCM,data:SBB4wv4IcL3QLAwblBLbY17BHk6xXRTspvu6uz4Adv3k2xAL0A9qiA==,iv:3ovjoJfQDq2NLrLB5PRc5L/0jKjGpY9pfqUc/YqVPIU=,tag:kzSgPqn8SolW7fx5nLm7ig==,type:str]
# gitlab dev secrets
gitlabClientID: ENC[AES256_GCM,data:T22zxjn0fJqTR+4DzoeZmKhPysMh4RrZ8q+pzinK3AgsXrr776AquSmKuRU+s1Qr8pKvJZ43GkhvKgGd1xxvWQ==,iv:A8qOqRo1Oa/NbwBFeDdtaOB2efFvcX9G/52f57X8qoQ=,tag:HnSa13nRkmwtXnuZ53hLUg==,type:str]
gitlabClientSecret: ENC[AES256_GCM,data:nlBZqj0hvcCdPnlBrj09CtIew2yn4WKsmrMp05ByhUfn0eAT4NWLbxHqldzNgXy9NxrxP/zEsa5CHJ8+hNNIng==,iv:GNnPxuHR2wVkqqyF4fHs7pvygJ2WMrzfngqTlEwUZJk=,tag:4NG5MQKS+finxfaX+AUM8w==,type:str]
# new relic license
newrelicLicenseKey: ENC[AES256_GCM,data:LOguPYtUNqQSgvJF21DTMp1/AmHj8QqJth4abnWATLVx1f8H1HtDog==,iv:BepUAwQMVKJUoOWSTyj554FzSktvhRovi7PD+2dWZXc=,tag:HGA/IXRaFq6Siw934idOqw==,type:str]
# rollbar access token
rollbarAccessToken: ENC[AES256_GCM,data:wQjQ0O2wG0YdOOVtGbFJ4BGKGHvYX9bw82yIv/jR9F0=,iv:DTHR8GJhVkMarsQe7X8TUKI6GMmIYky/jYRFFxebF08=,tag:LSzKZlpieaK10IOmQBomlg==,type:str]
# all these invalid secrets are here because of cfapi bugs!
logglyToken: ENC[AES256_GCM,data:3vgoxDR+giLX6hvNzw==,iv:LIHCLc45IpjeA3rl+5CQRDDNCisdFAZgctZdFXfos1I=,tag:Hm5BjweVSP4AUw0LRHksOg==,type:str]
bitbucketClientID: ENC[AES256_GCM,data:vkbpdMJfZ3mOkA==,iv:hcUFasdZNsaJpYEW7GM6XONqR4VWIFzd8PX2wDal6aY=,tag:hKuFzksTYkAEuGPwJQMO/Q==,type:str]
bitbucketClientSecret: ENC[AES256_GCM,data:m4xJ1LMi+LUr55gE0o4=,iv:IgoLeT9OQF/bPWaIXDUgaXb3EdLT2t+Mtrpq08GIgkg=,tag:HnU160GguIwiq89vCPH0AA==,type:str]
# CFCR registry auth API key
registryAuthKey: ENC[AES256_GCM,data:TDXSWd3kMFZeM1w1ejD2Ec3wrfJgdgt96zidx6xUj2M7qhpk,iv:/uVxJIideA1z55TVHu5dcQL2G5DQyAXMlkreAsG2nXA=,tag:i+ifPvzuQHmiTkJp8mh40g==,type:str]
# Internal Registry admin token
registryAdminToken: ENC[AES256_GCM,data:6oA+oYwopmqcdxXp/vQgnHpog2ycHoyAdzbftJShQEA=,iv:JVZ7B1C2YcR0NJcjdWSM12PZwt37Qo6tgZkxXK+BLAU=,tag:4eoWT5DnU1bsnHUmv+UvOA==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:839151377425:key/8f4d2cf9-30fb-4f16-a9a8-6cfb6815626e
        created_at: '2017-07-11T11:10:15Z'
        enc: AQICAHh7tK2dh55HkjrL+q3qHw1Fs/LKV7qodM1JtjJ3RA8cDwGeIbWVxKa6h3E713LqthRvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0U/aGaTv2XkekZBNAgEQgDuHYUmDX2R/EE/oKLdPNOxbxmtjgQbJt4l/xL+g3W1B/CLXjZh7G3dwZrMBhi8zU6J0hIbGd+fo2XSdtA==
    lastmodified: '2017-07-11T11:10:16Z'
    mac: ENC[AES256_GCM,data:A6ENyH8K3i8GX4CDrtrFCdHrQ28M7iKgjFWUhnREnJcgGS3mDZbv3SDtVBTdbjMXxcht87tQRLFQNnq/0E+FdLZ6JEOI44EF+VewMCZ4L30UxkS4N4r+NyCGihrTA1rpNrbP2ZCU8pQRKCKNOdhzcBrgCziRARAetLlM4vo3PSU=,iv:xHAHPaGyRlXDidEkIUyAm/eh03BS88zShbTzXRFYcSg=,tag:mWyaWH9HtIYqMjUcONT9/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 2.0.9
