{{ $name := printf "%v-%v-%v" .Release.Name .Values.global.codefresh "resource-limitations" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
data:
  resource-limitations.json: |
    {}