apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codefresh.fullname" . }}-registry
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
data:
  internal-registry.json: |
    {}
  additional-internal-registries.json: |
    []