{{- if and .Values.postgresqlCleanJob.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "codefresh.fullname" . }}-postgres-clean
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
stringData:
  PGHOST: {{ default (printf "%s-%s" .Release.Name .Values.global.postgresService) .Values.global.postgresHostname }}
  PGPORT: {{ .Values.global.postgresPort | default 5432 | quote }}
  PGDATABASE: {{ .Values.global.postgresDatabase | default "codefresh" }}
  PGUSER: {{ .Values.global.postgresUser }}
  PGPASSWORD: {{ .Values.global.postgresPassword }}
{{- end }}