apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
data:
  # example_property: some_value
  active: {{ default "" .Values.active | quote }}
  oauth-endpoint: {{ default "" .Values.oauthEndpoint | quote }}
  host: {{ .Values.host | quote }}
  client-id: {{ .Values.clientId | quote }}
  username: {{ .Values.username | quote }}