{{- if and .Values.rbacEnable .Values.rbacCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-codefresh-gencerts
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cf-codefresh-gencerts
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-codefresh-gencerts
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname" . }}-gencerts
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}-gencerts
    namespace: {{ .Release.Namespace }}

{{ end }}