{{- if  and .Values.rbacEnable .Values.rbacCreate }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: tools
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete      
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: tools-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tools
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
{{ end }}
