{{- if .Values.rbacEnable }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: tools
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  - "batch"
  resources:
  - configmaps
  - secrets
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tools-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tools
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
{{ end }}