{{- if and .Values.hooks.mongodb.enabled }}
{{- $libTemplateName := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
---
{{- $tolerations := .Values.hooks.mongodb.tolerations | default list }}
{{- $globalTolerations := .Values.global.tolerations | default list }}
{{- $allToleration := concat $globalTolerations $tolerations }}
{{- $affinity := .Values.hooks.mongodb.affinity | default dict }}
{{- $globalAffinity := .Values.global.affinity | default dict }}
{{- $allAffinity := mergeOverwrite $globalAffinity $affinity }}
{{- $nodeSelector := .Values.hooks.mongodb.nodeSelector | default dict }}
{{- $globalNodeSelector := .Values.global.nodeSelector | default dict }}
{{- $allNodeSelector := mergeOverwrite $globalNodeSelector $nodeSelector }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "codefresh.fullname" . }}-update-system-re
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 180
  template:
    metadata:
      name: {{ include "codefresh.fullname" . }}-update-default-re
      labels:
        {{ include "codefresh.labels" . | nindent 8 }}
    spec:
      {{- include (printf "%s.image.pullSecrets" $libTemplateName ) . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.hooks.mongodb.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "codefresh.fullname" . }}-update-system-re
        image: {{ include (printf "%s.image.name" $libTemplateName) (dict "image" .Values.hooks.mongodb.image "context" .) }}
        envFrom:
          - secretRef:
              name: {{ include "codefresh.fullname" . }}
        env:
          - name: MONGODB_HOST
          {{- include "codefresh.mongodb-host-env-var-value" . | indent 12 }}
          - name: MONGODB_USER
          {{- include "codefresh.mongodb-user-env-var-value" . | indent 12 }}
          - name: MONGODB_PASSWORD
          {{- include "codefresh.mongodb-password-env-var-value" . | indent 12 }}
          - name: MONGO_URI_RE_MANAGER
          {{- include "codefresh.mongo-uri-re-manager-env-var-value" . | indent 12 }}
          - name: DIND_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.DIND_IMAGE) }}
          - name: ENGINE_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.ENGINE_IMAGE) }}
          - name: DOCKER_PUSHER_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.DOCKER_PUSHER_IMAGE) }}
          - name: DOCKER_PULLER_IMAGE
            value: {{  include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.DOCKER_PULLER_IMAGE) }}
          - name: DOCKER_BUILDER_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.DOCKER_BUILDER_IMAGE) }}
          - name: CONTAINER_LOGGER_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.CONTAINER_LOGGER_IMAGE) }}
          - name: GIT_CLONE_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.GIT_CLONE_IMAGE) }}
          - name: DOCKER_TAG_PUSHER_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.DOCKER_TAG_PUSHER_IMAGE) }}
          - name: FS_OPS_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.FS_OPS_IMAGE) }}
          - name: COMPOSE_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.COMPOSE_IMAGE) }}
          - name: KUBE_DEPLOY
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.KUBE_DEPLOY) }}
          - name: TEMPLATE_ENGINE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.TEMPLATE_ENGINE) }}
          - name: PIPELINE_DEBUGGER_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.PIPELINE_DEBUGGER_IMAGE) }}
          - name: CR_6177_FIXER
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.CR_6177_FIXER) }}
          - name: GC_BUILDER_IMAGE
            value: {{ include "codefresh.buildImageName" (dict "registry" .Values.global.imageRegistry "imageFullName" .Values.runtimeImages.GC_BUILDER_IMAGE) }}
        command:
          - "/bin/bash"
          - "-c"
          - |
            {{ .Files.Get "files/updateSystemReImages.sh" | nindent 12  }}
        resources:
          {{- toYaml .Values.hooks.mongodb.resources | nindent 10 }}
        volumeMounts:
        {{- include (printf "%s.volumeMounts" $libTemplateName) (dict "Values" .Values.hooks.mongodb.volumeMounts "context" $) | indent 10 }}
      {{- with $allNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $allAffinity }}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- with $allToleration }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      {{- include (printf "%s.volumes" $libTemplateName) (dict "Values" .Values.hooks.mongodb.volumes "context" $) | indent 8 }}
      restartPolicy: Never
{{- end }}
