imagePullPolicy: Always
redeploy: false

# Number of replicas
replicaCount: 1

image: r.cfcr.io/codefresh-inc/codefresh/segment-reporter
imageTag: master

# Service type (ClusterIP, NodePort, LoadBalancer)
#serviceType: ClusterIP

# Service port
port: 80

# Pod (target) port
targetPort: 9000

blacklistUsers: ""
eventbusInterval: 5

####################
# local develpment #
####################

# program the program that should be executed, relative to the executed working directory
program: index.js