imagePullPolicy: Always
redeploy: false
replicaCount: 1
image: r.cfcr.io/codefresh-inc/codefresh/cf-tls-sign
imageTag: master
port: 4999
certVolumeSize: 3Gi

# Service type (ClusterIP, NodePort, LoadBalancer)
#serviceType: ClusterIP