seed:
  mongoSeedJob:
    mongodbRootURI: mongodb://root:XT9nmM8dZDZ@mongodb:27017/?authSource=admin
    mongodbRootOptions: authSource=admin
    mongodbRootPassword: XT9nmM8dZDZ

global:
  appUrl: ""  # placeholder for ${CF_APP_HOST}
  firebaseSecret: ""  # placeholder for ${FIREBASE_SECRET}

  mongoURI: "mongodb://mongodb:27017/?ssl=true&authMechanism=MONGODB-X509&authSource=$external"
  redisUrl: cf-redis
  postgresPort: 6432

  volumes:
    mongodb-client-cert:
      enabled: true
      type: secret
      optional: true
      nameOverride: mongodb-client-cert
    redis-tls:
      enabled: true
      type: secret
      optional: true
      nameOverride: cf-redis-crt

  volumeMounts:
    mongodb-client-cert:
      path:
      - mountPath: /etc/ssl/mongodb/client.pem
        subPath: client.pem
    redis-tls:
      path:
      - mountPath: /etc/ssl/redis

  env:
    # Mongo MTLS
    MONGODB_SSL_ENABLED: true
    MTLS_CERT_PATH: /etc/ssl/mongodb/client.pem
    RUNTIME_MTLS_CERT_PATH: /etc/ssl/mongodb/client.pem
    RUNTIME_MONGO_TLS: "true"
    RUNTIME_MONGO_TLS_VALIDATE: "false"
    MONGO_MTLS_VALIDATE: "false"
    # Redis MTLS
    REDIS_TLS: true
    REDIS_REJECT_UNAUTHORIZED: false
    REDIS_TLS_SKIP_VERIFY: true
    REDIS_CA_PATH: /etc/ssl/redis/ca.crt
    REDIS_CLIENT_CERT_PATH : /etc/ssl/redis/tls.crt
    REDIS_CLIENT_KEY_PATH: /etc/ssl/redis/tls.key

ingress:
  enabled: true
  ingressClassName: nginx
  tls:
    enabled: false

mongodb:
  enabled: false

redis:
  tls:
    enabled: true
    autoGenerated: true
    authClients: true

postgresql:
  containerPorts:
    postgresql: 6432
  primary:
    service:
      ports:
        postgresql: 6432

secrets:
  ext-redis:
    enabled: true
    stringData:
      redis-url: cf-redis
      redis-password: hoC9szf7NtrU

extraResources:
- apiVersion: v1
  kind: Service
  metadata:
    name: cf-redis
  spec:
    ports:
    - name: tcp-redis
      port: 6379
      protocol: TCP
      targetPort: redis
    selector:
      app.kubernetes.io/component: master
      app.kubernetes.io/instance: cf
      app.kubernetes.io/name: redis
    type: ClusterIP

seed-e2e:
  enabled: false
