{{- if not (include "mongodb.existingPvc" . ) -}}

{{- $storageClass :=  ( include "mongodb.storageClass" . ) -}}
{{- $storageSize :=  ( include "mongodb.storageSize" . ) -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ $storageSize | quote }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}
{{- end }}