apiVersion: v1
kind: Service
metadata:
  {{- if  or .Values.global.onprem .Values.global.dynamic }}
  name: mongodb
  {{- else -}}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: {{ template "fullname" . }}
