apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
data:
  providers.json: |
{{ .Values.providersData | indent 4 }}
{{- if .Values.deploymentTemplateImages }}
  deploymentTemplateImages.json: |
{{ .Values.deploymentTemplateImages | indent 4 }}
{{- end }}
