{{- if .Values.global.seedJobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-seed-mongo
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-seed-mongo
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
    spec:
      containers:
      - name: {{ template "fullname" . }}-admincf
        image: {{ .Values.mongodbImage }}
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGODB_ROOT_PASSWORD
            value: {{ .Values.mongodb.mongodbRootPassword }}
          - name: MONGODB_ADDRESS
            value: {{ .Release.Name }}-{{ .Values.global.mongoService }}:{{ .Values.global.mongoPort }}
          - name: MONGODB_DATABASE
            value: {{ .Values.global.mongodbDatabase }}
          - name: MONGODB_USER
            value: {{ .Values.global.mongodbUsername }}
          - name: MONGODB_PASSWORD
            value: {{ .Values.global.mongodbPassword }}
        command:
          - "/bin/sh"
          - "-exc"
          - |
{{ .Files.Get (print .Values.global.mongoSeedJobScript ) | indent 12  }}
        volumeMounts:
        - name: seed
          mountPath: "/etc/admin/accounts.json"
          subPath: "accounts.json"
        - name: seed
          mountPath: "/etc/admin/users.json"
          subPath: "users.json"
      restartPolicy: OnFailure
      volumes:
      - name: seed
        configMap:
          name: {{ template "fullname" . }}
{{- end }}
