{{- if not (include "mongodb.existingPvc" . ) -}}

{{- $storageClass :=  ( include "mongodb.storageClass" . ) -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  annotations:
    {{- if $storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ $storageClass | quote }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}