version: 0.0.1

components:
- name: cfapi
  spec:
    git: &git
      owner: codefresh-io
      repo: cf-helm
      revision: master
      path: codefresh/local-charts/cfapi/component.yaml.tmpl
  values:
    - git: &nodejs-local-values
        <<: *git
        path: codefresh/env/dynamic/nodejs-local-values.yaml
    - git:
        <<: *git
        # need some extra values from cfapi values
        path: codefresh/local-charts/cfapi/values.yaml
- name: context-manager
  spec:
    git: 
     <<: *git
     path: codefresh/local-charts/context-manager/component.yaml.tmpl
  values:
    - git: *nodejs-local-values
- name: pipeline-manager
  spec:
    git: 
     <<: *git
     path: codefresh/local-charts/pipeline-manager/component.yaml.tmpl
  values:
    - git: *nodejs-local-values
