version: 0.0.1

components:
- name: cfapi
  spec:
    git: &git
      owner: codefresh-io
      repo: cf-helm
      revision: master
      path: codefresh/env/dynamic/nodejs-local-values.yaml
  values:
    - git: *git
    - git:
        <<: *git
        # need some extra values from cfapi values
        path: codefresh/local-charts/cfapi/values.yaml
- name: context-manager
  spec:
    git: *git
  values:
    - git: *git
- name: pipeline-manager
  spec:
    git: *git
  values:
    - git: *git
