{{ $name := printf "%v-%v-%v" .Release.Name .Values.global.codefresh "runtime-envs" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
data:
  runtimeEnvironments.json: |
{{ include "runtime-environment-config" . | indent 4 }}
