apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-update-default-re
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
  annotations:
    {{- if $.Values.global.mongoTLS }} # run hook after mongodb-tls secret is created
    "helm.sh/hook": post-upgrade
    {{- else }}
    "helm.sh/hook": pre-upgrade
    {{- end }}
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-update-default-re
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
    spec:
      {{- if .Values.global.privateRegistry }}
      imagePullSecrets:
        - name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-registry"
      {{- end }}
      containers:
      - name: {{ template "fullname" . }}-update-default-re
        {{- if .Values.global.privateRegistry }}
        image: "{{ .Values.global.dockerRegistry }}{{ .Values.global.mongodbImage }}"
        {{- else }}
        image: {{ .Values.global.mongodbImage }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        env:
          {{- if .Values.global.env }}
          {{- range $key, $value := .Values.global.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end}}
          {{- end}}
          - name: MONGO_URI_RE_MANAGER
            value: {{ include "calculateMongoURI" (dict "dbName" "runtime-environment-manager" "mongoURI" .Values.global.mongoURI) }}
          - name: DIND_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.DIND_IMAGE) }}
          - name: ENGINE_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.ENGINE_IMAGE) }}
          - name: DOCKER_PUSHER_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.DOCKER_PUSHER_IMAGE) }}
          - name: DOCKER_PULLER_IMAGE
            value: {{  include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.DOCKER_PULLER_IMAGE) }}
          - name: DOCKER_BUILDER_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.DOCKER_BUILDER_IMAGE) }}
          - name: CONTAINER_LOGGER_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.CONTAINER_LOGGER_IMAGE) }}
          - name: GIT_CLONE_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.GIT_CLONE_IMAGE) }}
          - name: DOCKER_TAG_PUSHER_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.DOCKER_TAG_PUSHER_IMAGE) }}
          - name: FS_OPS_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.FS_OPS_IMAGE) }}
          - name: COMPOSE_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.COMPOSE_IMAGE) }}
          - name: KUBE_DEPLOY
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.KUBE_DEPLOY) }}
          - name: TEMPLATE_ENGINE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.TEMPLATE_ENGINE) }}
          - name: PIPELINE_DEBUGGER_IMAGE
            value: {{ include "buildImageName" (dict "registry" .Values.global.dockerRegistry "imageFullName" .Values.runtimeImages.PIPELINE_DEBUGGER_IMAGE) }}
        command:
          - "/bin/bash"
          - "-c"
          - |
{{ .Files.Get "files/on-prem/updateDefREImgScript" | indent 12  }}
        volumeMounts:
        {{- if $.Values.global.mongoTLS }}
        - mountPath: /etc/ssl/mongodb/
          name: mongodb-tls
          readOnly: true
        {{- end }}
      volumes:
      {{- if $.Values.global.mongoTLS }}
      - name: mongodb-tls
        secret:
          secretName: {{ $.Release.Name }}-{{ $.Values.global.codefresh }}-mongodb-tls
      {{- end }}
      restartPolicy: Never
