{{- $mongoServer := printf "%s-%s.%s" .Release.Name .Values.mongodbService .Release.Namespace -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-seed-mongo
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-seed-mongo
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
    spec:
      containers:
      - name: {{ template "fullname" . }}-admin-account
        image: {{ .Values.mongoImage }}
        imagePullPolicy: IfNotPresent
        {{ if and ((.Values.mongodbUsername) (.Values.mongodbPassword)) }}
        command: ["/bin/sh", "-c", "mongoimport --host {{ $mongoServer }} --db {{ .Values.mongodbDatabase }} --username {{ .Values.mongodbUsername | quote }} --password {{ .Values.mongodbPassword | quote }} --collection accounts --type json --file /etc/admin/accounts.json"]
        {{ else }}
        command: ["/bin/sh", "-c", "mongoimport --host {{ $mongoServer }} --db {{ .Values.mongodbDatabase }} --collection accounts --type json --file /etc/admin/accounts.json"]
        {{ end }}
        volumeMounts:
        - name: seed
          mountPath: "/etc/admin/accounts.json"
          subPath: "accounts.json"
      - name: {{ template "fullname" . }}-admin-user
        image: {{ .Values.mongoImage }}
        imagePullPolicy: IfNotPresent
        {{ if and ((.Values.mongodbUsername) (.Values.mongodbPassword)) }}
        command: ["/bin/sh", "-c", "mongoimport --host {{ $mongoServer }} --db {{ .Values.mongodbDatabase }} --username {{ .Values.mongodbUsername | quote }} --password {{ .Values.mongodbPassword | quote }} --collection users --type json --file /etc/admin/users.json"]
        {{ else }}
        command: ["/bin/sh", "-c", "mongoimport --host {{ $mongoServer }} --db {{ .Values.mongodbDatabase }}  --collection users --type json --file /etc/admin/users.json"]
        {{ end }}
        volumeMounts:
        - name: seed
          mountPath: "/etc/admin/users.json"
          subPath: "users.json"
      restartPolicy: OnFailure
      volumes:
      - name: seed
        configMap:
          name: {{ template "fullname" . }}
