{{- if not (include "rabbitmq.existingPvc" . ) -}}

{{- $storageClass :=  ( include "rabbitmq.storageClass" . ) -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "rabbitmq.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if $storageClass }}
  storageClassName: $storageClass
  {{- end }}  

{{- end }}
