{{- if not (include "rabbitmq.existingPvc" . ) -}}

{{- $storageClass :=  ( include "rabbitmq.storageClass" . ) -}}
{{- $storageSize :=  ( include "rabbitmq.storageSize" . ) -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "rabbitmq.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ $storageSize | quote }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}  

{{- end }}
