---
# records to /etc/hosts of the containers
# hostsApp: default empty

# customize consul chart
consul:
  DatacenterName: minikube
  Replicas: 1
  Memory: 256Mi

# use smaller registry storage
registry:
  storageSize: 4Gi


# cstomize runtime environments
runtime_envs:
  - name: codefresh-inc
    inCluster: true
    selectorRuntimeEnv: codefresh-inc
    namespace: dinds