---
# records to /etc/hosts of the containers
# hostsApp: default empty

firebaseUrl: "https://codefresh-on-prem.firebaseio.com/on-prem"

# customize consul chart
consul:
  DatacenterName: minikube
  Replicas: 1
  Memory: 64Mi

postgresql:
  resources:
    requests:
      memory: 128Mi

mongodb:
  resources:
    requests:
      memory: 64Mi

redis:
  resources:
    requests:
      memory: 64Mi

# use smaller registry storage
registry:
  storageSize: 4Gi

builder:
  replicaCount: 1

# cstomize runtime environments
runtime_envs:
  - name: codefresh-inc
    inCluster: true
    selectorRuntimeEnv: codefresh-inc
    namespace: dinds

tags:
  saas: false
  infra: true

