# number of replicas
# by default 2
# replicaCount: 2

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# dind container port (1300 - default)
containerPort: 1300

