{{- if index .Values "argo-platform" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson .Values.dockerconfigjson | b64enc | quote }}
{{- end }}