apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-environments
  labels:
    {{ include "codefresh-gitops.labels" . | nindent 4 }}
data:
  runtimeEnvironments.json: |
{{ include "runtime-environment-config" . | indent 4 }}
