{{ $name := printf "%v-%v" (include "codefresh-gitops.fullname" .) "version-info" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{ include "codefresh-gitops.labels" . | nindent 4 }}
data:
  app: {{ .Chart.Version | default "unknown" }}
  {{- range $i, $dep := .Chart.Dependencies }}
  {{ $dep.Name }}: {{ $dep.Version | quote }}
  {{- end }}
