apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Values.imageTag | quote }}
    spec:
      imagePullSecrets:
        - name: "{{ .Release.Name }}-{{ .Values.codefreshService }}-registry"
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}" 
              key: app-url
        - name: API_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}" 
              key: app-protocol
        - name: INTERNAL_API_URI
          value: "http://{{ .Release.Name }}-{{ .Values.cfapiService }}:{{ .Values.cfapiInternalPort }}:"
        - name: MONGO_SERVICE
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: mongodb-service
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: mongodb-port
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: mongodb-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: mongodb-password
        - name: MONGO_DATABASE
          value: {{ .Values.mongoDatabase | quote }}
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@{{ .Release.Name }}-$(MONGO_SERVICE).{{ .Release.Namespace }}:$(MONGO_PORT)/$(MONGO_DATABASE)"
        - name: NEWRELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: newrelic-license-key
        - name: RABBIT_SERVICE
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: rabbitmq-service
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: rabbitmq-password
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: rabbitmq-username
        - name: EVENTBUS_URI
          value: "amqp://$(RABBIT_USER):$(RABBIT_PASSWORD)@{{ .Release.Name }}-$(RABBIT_SERVICE).{{ .Release.Namespace }}"
        - name: POSTGRES_SERVICE
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: postgres-service
        - name: POSTGRES_HOST
          value: "{{ .Release.Name }}-$(POSTGRES_SERVICE).{{ .Release.Namespace }}" 
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: postgres-database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: postgres-password
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SIGN_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.codefreshService }}"
              key: stripe-webhook-sign-secret