apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  # segment black list users
  segment-blacklist-users: {{ default "" .Values.segmentBlackList }}

  # Firebase url
  firebase-url: https://codefresh-on-prem.firebaseio.com/on-prem

  # CFCR
  cfcr-domain: {{ default "cfcr.staging.io" .Values.cfcrDomain }}

  # OAuth router callback
  oauth-router-callback: {{ default "http://codefresh-inc-3.cf-cd.com:2222/api/auth/github/callback/" .Values.oauthRouterCallback }}

  # GCE Project
  google-compute-engine-project: {{ default "savvy-badge-103912" .Values.gceProject }}