apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
data:
  # segment black list users
  segment-blacklist-users: {{ default "" .Values.segmentBlackList | quote }}

  # Firebase url
  firebase-url: {{ .Values.firebaseUrl | quote }}

  # CFCR
  cfcr-domain: {{ .Values.global.cfcrDomain | quote }}

  # GCE Project
  google-compute-engine-project: {{ .Values.global.gceProject | quote }}
