---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-resource-limitations
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
data:
  resource-limitations.json: |
    {
      "cpuShares": {
          "value": 128,
          "compose": {
              "v1": "cpu_shares",
              "v2": "cpu_shares",
              "v2.1": "cpu_shares"
          },
          "container": "CpuShares",
          "build": "cpushares"
      },
      "cpuPeriod": {
          "value": 10000,
          "compose": {

          },
          "container": "CpuPeriod",
          "build": "cpuperiod"
      },
      "memory": {
          "value": 1572864000,
          "compose": {
              "v1": "mem_limit",
              "v2": "mem_limit",
              "v2.1": "mem_limit  "
          },
          "container": "Memory",
          "build": "memory"
      },
      "memorySwap": {
          "value": -1,
          "compose": {
              "v1": "memswap_limit",
              "v2": "memswap_limit",
              "v2.1": "memswap_limit"
          },
          "container": "MemorySwap",
          "build": "memswap"
      }
    }