{{- if .Values.global.seedJobs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-seeds
  labels:
    app: {{ template "fullname" . }}-seeds
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
data:
  idps.json: |
    {
        "_id" : ObjectId("5b79a32e3b80d12608352f8e"),
        "clientName" : "local",
        "displayName" : "local",
        "tokenSecret" : "q9MNUmE6assnoANmGZEjtrAa",
        "clientType" : "localUserPassword",
        "accounts" : []
    }
  accounts.json: |
    {
        "_id" : ObjectId("59009117c102763beda7ce71"),
        "badgeToken" : "eyJhbGciOiJIUzI1NiJ9.NTkwMDkxMTdjMTAyNzYzYmVkYTdjZTcx.B0HOUL6HlpTRNr_e95pVucSRMRzP2cobe5kIoMtrDSc",
        "createdAt" : ISODate("2017-04-26T12:22:48.001+0000"),
        "updatedAt" : ISODate("2017-04-26T12:27:13.720+0000"),
        "name" : "admin-cf",
        "runtimeEnvironment" : "codefresh",
        "canUsePrivateRepos" : true,
        "dedicatedInfrastructure" : false,
        "cfcrRepositoryPath": "admin-cf",
        "build" : {
            "nodes" : NumberInt(0),
            "parallel" : NumberInt(1),
            "strategy" : "account"
        },
        "integrations" : {
            "stash" : {
                "active" : false
            },
            "registries" : [

            ]
        },
        "notifications" : [
            {
                "type" : "pr",
                "events" : [
                    "build-success"
                ]
            }
        ],
        "repoPermission" : "public",
        "environment" : NumberInt(1),
        "admins" : [
            ObjectId("59009221c102763beda7cf04")
        ],
        "localUserPasswordIDPEnabled": true,
        "__v" : NumberInt(0)
    }
  users.json: |
    {
        "_id" : ObjectId("59009221c102763beda7cf04"),
        "register_date" : ISODate("2017-04-26T12:27:13.608+0000"),
        "userName" : "AdminCF",
        "email" : "admin@codefresh.io",
        "defaultAccount" : NumberInt(0),
        "notifications" : [
            {
                "type" : "mail",
                "events" : [
                    "build-success",
                    "build-failure"
                ]
            }
        ],
        "logins": [{
            "idp": ObjectId("5b79a32e3b80d12608352f8e")
        }],
        "status" : "new",
        "account" : [
            ObjectId("59009117c102763beda7ce71")
        ],
        "roles" : [
            "User",
            "Admin"
        ],
        "key" : {
            "key" : "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAz6JQxcFORE6KwmBO1UnfpCph/PyARfm65eYXRuCOzdv5EIcz\n+4rRBwooH/SR8Wq49QRjq+Qm6ce2EBj2HD57t4rMj3W6X+5CwoFRXfF0tB4GqPSe\nDagbrNJbx93/dbEM+qEZNFk1MxtoJcBmj3jfrlGdTrarR3VOeBgKVLm/+Wz36pjM\nI4utzupHFAPquSIz0jis02/vccIZ8rAtyVdCd1q6Wz5DVu6iuGyMCYrpa9MFcupR\nc2eggyZ6PyNhmKuP7twr7y22elDQDkSo0G2yv4qbZnHEmShHhO/PKePMETUYMRvM\nzSS9qndT+Nax8vQvxeOCN3cEwm/Jy1oboYiwAwIDAQABAoIBAHyAJpC9nXGl6tws\npXiNKFWmuETbHwtWeDQcKL7uLZLQoOLBP3FIRphDBdZLbytkQ+1fKWjLkG3Du66h\nWQmMieB/kLNA83VMR6mboy+Cdej+zB2JODCWKaoSJMiOm/x1IoQyDwvtpdG0UFm6\nqYTEBNPgykOFkuRxOZEXUTKGgs9K7CFt1TbN8/bGCLgdq9plH2OvlOZkr4Cz0LpS\ns+Y/QJ/H4DDNZ6538NYLpq40Qi2NNq7iFJQ3iddEDi0i5O7pJK3Lziin/h3m99a+\nDbQET1bHm5Jh+Nrfxh1iwHaXdQLLoz5cex/ie5H6jtEMCSdcd53sPivSyHwMprEm\ng+0sNnECgYEA7q1eYNGJoA/UNXotVjPCaArf9/s1xiOTr5Fv1nWkH0jkmrj0WdjB\nsLQByC/wjSmZpfcKp38Z3JDFUimUEuCtZzgBCN6JB6VXe1t3L0wI1VTnxJwvsk8V\nQCB/gTugIDE1oE97kTvDuGl74XyY7uHyA1aYiXVnJ0bw8mcNCW2EzZkCgYEA3rQp\n3JjBGxBXaz7yCfhoQn5YZXw5yMBngyP8emu8u+7excZvCqIG+8NVh5KGFApOw9oe\n0aHUXGgfhSsl+xFA/m+E56mxm/J1PqRrWbnaEkLzPRSoFJBckjBm3ADHb6PuGbOL\nT72qxKPdZ1kdt0QfqIbZpR45COVk6KtmHMCO0/sCgYB6YaL2+fobfIJPOWptvPR9\n7LWSrdiQ1EUxzN0Plhqlf/bX7uY7+4y1Uldnkk1B1IbYNqfb4qwcEI9c5bzrQREo\nz+qX5aNVrE4DDo86TT5qRLLieUNrpmk7DG7UkQI1/4WDwb2WZpKgyFWg9QZl1q0F\nUS29rdlKpnF9maFxqBpkYQKBgBPU31VxlOCgF+jI9izFHiOttJl08oBaAd2/up/8\nMBZcMyJRhVnhC9Ynkto7xgzKzjDKn6vzSUHhU808BmnRI4SE0cT/a32DncUyRwz6\na9zscVSjHkSWhmfOP5qfxyK96loHjwRO04InRXQKj4beXiNXvtHhWxrbspy1hqZQ\nz2c5AoGBAO0tRNKfgoZH+sTiaphR550YFnIn8U9ROa1iQUvSiM0nHW6FraIR1sYB\nUTCtgOSJdffGMFrvH+PhShJPw7u3juZh9NBzrARjZPwBJyBaYDw3elVc3epZWoGC\n8EBEgdFVqFwPctkGvqyJ/5Zl3KnTioXxslHjP45H+Ne/nEWPejuP\n-----END RSA PRIVATE KEY-----\n",
            "pubKey" : "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPolDFwU5ETorCYE7VSd+kKmH8/IBF+brl5hdG4I7N2/kQhzP7itEHCigf9JHxarj1BGOr5Cbpx7YQGPYcPnu3isyPdbpf7kLCgVFd8XS0Hgao9J4NqBus0lvH3f91sQz6oRk0WTUzG2glwGaPeN+uUZ1OtqtHdU54GApUub/5bPfqmMwji63O6kcUA+q5IjPSOKzTb+9xwhnysC3JV0J3WrpbPkNW7qK4bIwJiulr0wVy6lFzZ6CDJno/I2GYq4/u3CvvLbZ6UNAORKjQbbK/iptmccSZKEeE788p48wRNRgxG8zNJL2qd1P41rHy9C/F44I3dwTCb8nLWhuhiLAD blabla\n"
        },
        "__v" : NumberInt(1),
        "last_login_date" : ISODate("2017-04-26T12:27:21.788+0000"),
        "hashedPassword" : "jRFgMK8CYVXa4FRBVsZQyWHdw/ErWSJzO/WKqdGcLpmeOZw8e6X5TvkYIkc617LU76RCB9B1jPNsbNVaTQGt4g==",
        "salt" : "GswhajDWen9vNW+fZ+xVbA=="
    }
{{- end }}
