{{- $registryService := printf "%s-%s.%s.svc:%v" .Release.Name .Values.global.registryService .Release.Namespace .Values.global.registryPort }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-registry
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
data:
  internal-registry.json: |
    {
      "kind": "standard",
      "domain": "{{ $registryService }}",
      "connection": {
        "protocol": "https",
        "caPath": "/etc/ssl/cf/ca.pem"
      }
    }
  additional-internal-registries.json: |
    []