apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "codefresh.fullname" . }}-runtime-envs
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
data:
  runtimeEnvironments.json: |
{{ include "runtime-environment-config" . | indent 4 }}
