{{- if .Values.global.seedJobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ template "fullname" . }}
        image: {{ .Values.global.mongodbImage }}
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGODB_ROOT_USER
            value: {{ .Values.global.mongodbRootUser }}
          - name: MONGODB_ROOT_PASSWORD
            value: {{ .Values.global.mongodbRootPassword }}
          - name: MONGODB_URI
            value: {{ .Values.global.mongoURI }}
          - name: MONGODB_DATABASE
            value: {{ .Values.mongodbName }}
          - name: MONGODB_USER
            value: {{ .Values.global.mongodbUsername }}
          - name: MONGODB_PASSWORD
            value: {{ .Values.global.mongodbPassword }}
        command:
          - "/bin/bash"
          - "-exc"
          - |
{{ .Files.Get (print .Values.mongoCreateDbJobScript ) | indent 12  }}
{{- end }}
