# number of replicas
# NOTE: cannot run more that 1 replica on single node cluster, like minikube
# by default 1
# replicaCount: 1

# image name
image: docker

# image tag  
imageTag: 17.05-dind

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# dind container port (1300 - default)
containerPort: 1300

# consul configuration (default: consul)
consulService: consul
# consul http port
consulHttpPort: 8500

# codefresh service name (chart name)
codefreshService: codefresh

# Codefresh APP URL
appUrl: codefresh.dev 