on:
  pull_request:
    types: [opened]
name: Add base branch label
jobs:
  base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Add base branch label
        uses: ffittschen/pr-branch-labeler@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}


